export const en = {
  appName: "Niria",
  appMotto: "The future of eye care starts with a photo.",
  appSubMotto: "Get rapid, AI-powered insights into your eye health from the comfort of your home.",
  footerText: "© TREASURES OF ZIMA LLC.",
  footerDisclaimer: "Niria is an informational tool and does not provide medical advice.",
  resultsDisclaimerShort: "Not medical advice. Consult a doctor.",
  resultsDisclaimer: "Important: The analysis provided by Niria is for informational purposes only and is not a substitute for a professional medical diagnosis. Always consult with a qualified ophthalmologist or healthcare provider for any eye health concerns or before making any decisions related to your health or treatment.",
  paymentPlaceholderText: "Our secure payment portal is coming soon. In a real application, this page would integrate with a payment processor like Stripe or PayPal to handle transactions securely.",

  home_ctaButton: "Start Analysis",
  home_whyChooseNiria: "Why Choose Niria?",
  home_mission_title: "Our Mission",
  home_mission_text: "To provide an intuitive, accessible, and affordable app that uses artificial intelligence to identify early signs in visual health and guide people to nearby specialists, promoting prevention as an act of care and personal autonomy.",
  home_vision_title: "Our Vision",
  home_vision_text: "For anyone in the world, regardless of their location, to be able to receive early guidance on their visual health through a reliable, accessible, and approachable tool.",
  home_fact_title: "Did you know...?",
  home_fact1: "At least 2.2 billion people have a vision impairment, and of these, at least 1 billion have a vision impairment that could have been prevented or has yet to be addressed.",
  home_fact2: "The leading global causes of vision loss are uncorrected refractive errors (≈42%) and cataracts (≈33%), both treatable with simple interventions.",
  home_fact3: "Diabetic retinopathy, common in people with diabetes, can prevent blindness in at least 90% of cases with timely diagnosis and treatment.",
  home_fact4: "Conditions like cataracts, glaucoma, and AMD increase the risk of falls in older adults by up to 38%.",
  home_testimonials_title: "Stories of Clarity and Care",

  feature_resultsInMinutes_title: "Results in Minutes",
  feature_resultsInMinutes_description: "Receive gentle, preliminary guidance on your eye health. Our AI provides a swift analysis of your photo, offering you timely clarity.",
  feature_noExpensiveEquipment_title: "No Expensive Equipment",
  feature_noExpensiveEquipment_description: "No special hardware is required. All you need is your smartphone to take the first step towards understanding your visual health.",
  feature_highAccuracyPotential_title: "High Accuracy Potential",
  feature_highAccuracyPotential_description: "Our service is powered by advanced AI to carefully recognize visual patterns, providing you with a reliable initial insight.",
  feature_securePrivate_title: "Secure & Private",
  feature_securePrivate_description: "Your trust is everything. Your photos and data are handled with the highest standards of privacy and security, always.",
  
  testimonial1_quote: "Living far from my mom, I was always worried about her health. Her complaining about her vision made me feel helpless. Niria was a game-changer. It was so easy for her to use, and the gentle alert gave us the clarity we needed to see a specialist nearby. It’s more than an app; it’s peace of mind.",
  testimonial1_name: "Laura G.",
  testimonial1_role: "The Worried Daughter",
  testimonial2_quote: "As a developer, my eyes are my most important tool. The constant screen time was causing strain, and I wanted a quick way to check in on my visual health without a full appointment. Niria is brilliant—fast, straightforward, and the results were presented clearly. It gave me the data I needed to be proactive.",
  testimonial2_name: "Daniel K.",
  testimonial2_role: "The Self-Care Tech",
  testimonial3_quote: "Keeping my independence is everything to me. I was looking for a simple way to keep an eye on my vision without complicated gadgets. Niria is wonderfully straightforward. The instructions are clear, and the report was easy to understand and share with my daughter. It’s a comforting tool to have.",
  testimonial3_name: "Margaret P.",
  testimonial3_role: "The Connected Senior",

  auth_loginToAccount: "Sign In to Your Account",
  auth_createAccount: "Create an Account",
  auth_firstNameLabel: "First Name",
  auth_firstNamePlaceholder: "Jane",
  auth_lastNameLabel: "Last Name",
  auth_lastNamePlaceholder: "Doe",
  auth_emailLabel: "Email Address",
  auth_emailPlaceholder: "you@example.com",
  auth_passwordLabel: "Password",
  auth_signInButton: "Sign In",
  auth_signUpButton: "Create Account",
  auth_googleSignInButton: "Sign in with Google",
  auth_loggingInButton: "Signing in...",
  auth_registeringButton: "Creating account...",
  auth_dontHaveAccount: "Don't have an account?",
  auth_signUpHereLink: "Sign Up",
  auth_alreadyHaveAccount: "Already have an account?",
  auth_signInHereLink: "Sign In",
  auth_orDivider: "OR",
  auth_forgot_password_link: "Forgot Password?",
  auth_reset_password_title: "Reset Password",
  auth_reset_password_instructions: "Enter the email address associated with your account, and we'll send you a link to reset your password.",
  auth_send_link_button: "Send Reset Link",
  auth_sending_link_button: "Sending Link...",
  auth_back_to_signin_link: "← Back to Sign In",
  auth_reset_link_sent: "Password reset link sent successfully. Please check your email inbox and spam folder.",
  auth_error_passwordsDoNotMatch: "Passwords do not match.",
  auth_error_loginFailed: "Login failed. Please check your credentials.",
  auth_error_registrationFailed: "Registration failed. Please try again.",
  auth_error_unexpected: "An unexpected error occurred. Please try again.",
  auth_error_email_in_use: "This email address is already in use by another account.",
  auth_error_weak_password: "Password is too weak. It should be at least 6 characters.",
  auth_error_user_not_found: "No account found with this email address.",
  auth_error_invalid_credentials: "Incorrect email or password. Please verify your credentials or try resetting your password.",
  auth_error_invalid_email: "The email address is not valid.",

  exam_title: "Eye Health Analysis",
  exam_instructions: "For best results, ensure your eye is well-lit and in focus. Remove glasses or contact lenses if possible. The image should clearly show your iris and pupil.",
  exam_uploadPhotoButton: "Upload Photo",
  exam_stopCameraButton: "Stop Camera",
  exam_takePhotoWithCameraButton: "Take Photo with Camera",
  exam_capturePhotoButton: "Capture Photo",
  exam_imagePreviewTitle: "Image Preview:",
  exam_livePreviewTitle: "Live Camera Preview",
  exam_analyzeButton: "Analyze Eye Photo",
  exam_analyzingText: "Analyzing your photo...",
  exam_error_fileTooLarge: "File is too large. Maximum size is 10MB.",
  exam_error_invalidFileType: "Invalid file type. Please upload a JPG, PNG, or WEBP image.",
  exam_error_noPhoto: "Please upload or take a photo of your eye first.",
  exam_error_cameraAccess: "Could not access camera. Please ensure permissions are granted.",
  exam_error_cameraNotSupported: "Camera not supported on this browser.",
  exam_error_analysisFailed: "An error occurred during the analysis. Please check your connection and try again.",
  exam_error_missingData: "User data or health questionnaire is missing. Please restart the process from the home page.",
  exam_error_invalid_image_data: "The provided image data is invalid. Please try capturing or uploading the photo again.",
  exam_retakePhotoButton: "Retake Photo",
  exam_cancelButton: "Cancel",
  exam_processing_image: "Processing image...",
  exam_instructions_title: "Instructions for Capturing Your Eye Image",
  exam_instructions_step1: "Clean your camera lens before you begin.",
  exam_instructions_step2: "Position yourself in a well-lit area, preferably near a window.",
  exam_instructions_step3: "Avoid direct sunlight and do not use a flash.",
  exam_instructions_step4: "Open both eyes as wide as possible and look directly at the camera.",
  exam_instructions_step5: "If possible, ask for assistance from another person to ensure both eyes are centered and visible in the image.",
  exam_instructional_video_aria: "Instructional video for eye capture",
  exam_mask_instruction: "Align your eyes within the ovals for the best results.",

  consent_title: "Informed Consent for Data Collection",
  consent_intro: "Before proceeding, please read and accept the following terms regarding the collection and use of your data.",
  consent_purpose_title: "Purpose of Data Collection",
  consent_purpose_text: "We will collect personal and medical information through the health questionnaire and the eye photo you provide. This data is essential for our AI to perform a preliminary analysis of your eye health.",
  consent_confidentiality_title: "Confidentiality and Security",
  consent_confidentiality_text: "Your information will be stored securely and handled with the strictest confidentiality. It will only be used for the purpose of this analysis and to improve our services. We do not sell your personal data.",
  consent_not_a_diagnosis_title: "Not a Medical Diagnosis",
  consent_not_a_diagnosis_text: "This analysis is an informational tool, not a substitute for a professional medical diagnosis. Always consult a qualified healthcare provider for any health concerns.",
  consent_acceptance_text: "By clicking 'Accept and Continue', you confirm that you have read, understood, and agree to the collection and use of your data as described above.",
  consent_accept_button: "Accept and Continue",
  consent_decline_button: "I Decline",
  consent_declined_title: "Consent Required",
  consent_declined_message: "You must accept the terms to proceed with the eye health analysis. You can restart the process from the home page if you change your mind.",

  questionnaire_title: "Patient Health Questionnaire",
  questionnaire_intro: "Please answer the following questions to provide context for your analysis.",
  questionnaire_submitButton: "Continue to Photo Capture",
  questionnaire_next_button: "Next",
  questionnaire_previous_button: "Previous",
  questionnaire_progress_step: "Step {current} of {total}",
  
  q_option_other_not_sure: "Other / Not sure",
  
  q_firstNameLabel: "First Name",
  q_firstNamePlaceholder: "Jane",
  q_lastNameLabel: "Last Name",
  q_lastNamePlaceholder: "Doe",
  q_cityLabel: "City",
  q_cityPlaceholder: "e.g., New York",
  q_stateLabel: "State",
  q_statePlaceholder: "e.g., NY",
  q_dob_label: "Date of Birth",
  q_dob_day_placeholder: "Day",
  q_dob_month_placeholder: "Month",
  q_dob_year_placeholder: "Year",
  month_january: "January",
  month_february: "February",
  month_march: "March",
  month_april: "April",
  month_may: "May",
  month_june: "June",
  month_july: "July",
  month_august: "August",
  month_september: "September",
  month_october: "October",
  month_november: "November",
  month_december: "December",

  q1_label_new: "1. What is the reason for taking this evaluation?",
  q1_option_blurry: "Blurry or altered vision",
  q1_option_tired: "Tired or fatigued eyes",
  q1_option_redness: "Redness or irritation",
  q1_option_checkup: "Periodic check-up",

  q2_label: "2. Do you wear lenses (glasses or contact lenses)?",
  q2_yes: "Yes",
  q2_no: "No",
  q2_other: "Other / Not sure",
  q2_satisfactionLabel: "If so, how satisfied are you with them?",
  q2_satisfactionPlaceholder: "e.g., They work well, I get headaches...",
  q2_lastUpdateLabel: "When was the last time you had your prescription updated?",
  q2_lastUpdatePlaceholder: "e.g., 6 months ago, over 2 years ago...",
  q3_label: "3. Have you ever had eye surgery, a major injury or trauma, or a serious eye infection?",
  q3_detailsLabel: "If yes, please provide details.",
  q3_detailsPlaceholder: "e.g., LASIK in 2018, corneal scratch...",
  q4_label: "4. Do you have any major general illnesses?",
  q4_illness_diabetes: "Diabetes",
  q4_illness_highBloodPressure: "High Blood Pressure",
  q4_illness_highCholesterol: "High Cholesterol",
  q4_illness_thyroid: "Thyroid Disease",
  q4_illness_arthritis: "Arthritis",
  q5_label: "5. Does anyone in your immediate family have any significant eye conditions?",
  q5_condition_glaucoma: "Glaucoma",
  q5_condition_macularDegeneration: "Macular Degeneration",
  q5_condition_strabismus: "Strabismus",
  q5_condition_highMyopia: "High Myopia",
  q6_label: "6. In addition to your main complaint, have you experienced any of the following symptoms?",
  q6_symptom_pain: "Pain",
  q6_symptom_itching: "Itching",
  q6_symptom_burning: "Burning",
  q6_symptom_tearing: "Excessive tearing",
  q6_symptom_gritty: "Gritty sensation",
  q6_symptom_lightSensitivity: "Sensitivity to light",
  q6_symptom_doubleVision: "Double vision",
  q6_symptom_none: "None of the above",

  q_screenTime_label: "7. On average, how many hours a day do you spend in front of a computer or digital screen?",
  q_screenTime_placeholder: "Select an option",
  q_screenTime_option_0_2: "Less than 2 hours",
  q_screenTime_option_2_4: "2-4 hours",
  q_screenTime_option_4_8: "4-8 hours",
  q_screenTime_option_8_plus: "More than 8 hours",
  
  error_validation_name: "Please enter your first and last name.",
  error_validation_dob_full: "Please select your complete date of birth (day, month, and year).",
  error_validation_state: "Please select a state.",

  results_title: "Your Eye Health Analysis",
  results_summaryTitle: "AI-Powered Summary",
  results_detailedFindingsTitle: "Detailed Findings from Image Analysis",
  results_noResults: "No analysis results to display.",
  results_riskLevelSuffix: "Risk",
  results_importantDisclaimerTitle: "Important Disclaimer",
  results_generalEyeHealthTipsTitle: "General Eye Health Tips",
  results_fetchingTips: "Fetching tips...",
  results_error_couldNotLoadTips: "Could not load eye health tips at this time. Please try again later.",
  results_refreshTipsButton: "Refresh Tips",
  results_proceedToPaymentButton: "Proceed to Payment",
  results_performAnotherAnalysisButton: "Perform Another Analysis",
  results_backToHomeButton: "Back to Home",
  results_loadingSummary: "Loading summary...",
  results_error_loading: "We were unable to load your results. If you have already paid, please",
  results_download_for_details: "For a detailed breakdown of your questionnaire, image analysis, and a list of local specialists, please download the full PDF report.",

  results_condition_cataract: "Cataract Development",
  results_details_cataract: "Slight lens opacity observed, recommend monitoring.",
  results_condition_glaucomaIndicators: "Glaucoma Indicators",
  results_details_glaucomaIndicators: "Visual signs that may be associated with glaucoma, such as changes to the optic nerve or iris.",
  results_condition_ptosis: "Ptosis (Droopy Eyelid)",
  results_details_ptosis: "The upper eyelid is lower than it should be, which may affect vision.",
  results_condition_subconjunctivalHemorrhage: "Subconjunctival Hemorrhage",
  results_details_subconjunctivalHemorrhage: "A broken blood vessel on the surface of the eye, often harmless but should be checked.",
  results_condition_conjunctivitis: "Infection / Conjunctivitis",
  results_details_conjunctivitis: "Signs of inflammation or infection of the conjunctiva (pink eye), such as redness and discharge.",
  results_condition_abnormalPupils: "Abnormal Pupils",
  results_details_abnormalPupils: "Pupils appear unequal in size, misshapen, or have an unusual color, requiring medical evaluation.",
  results_condition_ocularJaundice: "Ocular Jaundice",
  results_details_ocularJaundice: "Yellowing of the white part of the eye, which can indicate liver issues.",
  results_condition_cornealArcus: "Corneal Arcus",
  results_details_cornealArcus: "A white, grey, or blue ring around the cornea, sometimes associated with high cholesterol.",
  results_condition_inflammation: "Inflammation / Redness",
  results_details_inflammation: "General signs of inflammation, significant redness, or discharge detected.",
  results_condition_drynessOrTearing: "Dryness / Abnormal Tearing",
  results_details_drynessOrTearing: "Visual signs that may indicate issues with tear production, such as excessive dryness or watering.",
  
  results_risk_low: "Low",
  results_risk_medium: "Medium",
  results_risk_high: "High",
  results_risk_undetermined: "Undetermined",

  payment_title: "Secure Payment",
  payment_unlock_title: "Unlock Your Full Report",
  payment_unlock_description: "For a one-time payment, get a downloadable PDF of your detailed analysis and keep it for your records.",
  payment_pay_now_button: "Pay $10.00 Now",
  payment_processing: "Processing...",
  payment_support_prompt: "Problems with your payment?",
  payment_support_link: "Contact Support",

  header_welcomeMessage: "Welcome, {email}",
  header_logoutButton: "Logout",
  header_loginRegisterButton: "Sign In / Sign Up",
  header_myProfileLink: "My Profile",
  header_adminPanel: "Admin Panel",
  header_doctorPortal: "Doctor Portal",
  header_hrAdminPanel: "HR Panel",

  profile_title: "My Profile",
  profile_personal_info_title: "Personal Information",
  profile_medical_info_title: "Medical Information",
  profile_upcoming_evaluation_title: "Upcoming Evaluation",
  profile_history_title: "Evaluation History",
  profile_tab_personal_info: "Personal Info",
  profile_tab_consultation: "Consultation & Reminders",
  history_evaluationDate: "Evaluation Date",
  profile_noHistory: "You have no past evaluations.",
  profile_loading: "Loading your profile...",
  profile_fetchError: "Could not load your profile. Please try again later.",
  profile_doctor_note_title: "Doctor's Note",
  profile_edit_button: "Edit Profile",
  profile_save_button: "Save Changes",
  profile_saving_button: "Saving...",
  profile_cancel_button: "Cancel",
  profile_change_photo_button: "Change Photo",
  profile_change_photo_prompt: "Click below to upload a new profile picture.",
  profile_uploading_photo: "Uploading...",
  profile_error_upload: "Error uploading photo.",
  profile_error_save: "Error saving profile.",
  profile_label_phone: "Phone Number",
  profile_placeholder_phone: "(555) 123-4567",
  profile_label_allergies: "Allergies",
  profile_placeholder_allergies: "e.g., Pollen, Penicillin",
  profile_label_conditions: "Medical Conditions",
  profile_placeholder_conditions: "e.g., Type 2 Diabetes",
  profile_label_surgeries: "Past Surgeries",
  profile_placeholder_surgeries: "e.g., Appendix removal (2015)",
  profile_label_assigned_doctor: "Assigned Doctor/Specialist",
  profile_placeholder_doctor: "e.g., Dr. Garcia",
  profile_label_next_consultation: "Next Scheduled Consultation",
  profile_label_enable_reminders: "Enable Evaluation Reminders",
  profile_countdown_due_in_days: "Due in {days} days",
  profile_countdown_due_today: "Due Today",
  profile_countdown_overdue: "Overdue",
  profile_countdown_no_date: "Not scheduled",

  admin_title: "Admin Dashboard",
  admin_manageUsers: "Manage Users",
  admin_error_load_users: "Could not load user list. You may not have permission.",
  admin_success_role_update: "User role updated successfully.",
  admin_error_role_update: "An error occurred while changing the role.",
  admin_error_self_remove: "You cannot remove your own admin status.",
  admin_table_header_user: "User",
  admin_table_header_role: "Role",
  admin_table_header_action: "Action",
  admin_role_admin: "Admin",
  admin_role_user: "User",
  admin_role_premium: "Premium",
  admin_role_doctor: "Doctor",
  admin_role_hr_admin: "HR Admin",
  admin_no_name: "No Name",
  admin_action_remove: "Remove Admin",
  admin_action_make: "Make Admin",
  admin_action_make_premium: "Make Premium",
  admin_action_remove_premium: "Remove Premium",
  admin_action_make_doctor: "Make Doctor",
  admin_action_remove_doctor: "Remove Doctor",
  admin_action_make_hr_admin: "Make HR Admin",
  admin_action_remove_hr_admin: "Remove HR Admin",
  admin_success_premium_update: "Premium status updated successfully.",
  admin_error_premium_update: "An error occurred while changing premium status.",
  admin_tab_users: "User Management",
  admin_tab_feedback: "Feedback",
  admin_tab_stats: "Dashboard",
  admin_feedback_title: "User Feedback",
  admin_feedback_table_header_rating: "Rating",
  admin_feedback_table_header_comment: "Comment",
  admin_feedback_table_header_date: "Date",
  admin_search_placeholder: "Search by name or email...",
  admin_no_users_found: "No users found.",
  admin_no_users_match: "No users match your search.",
  admin_feedback_filter_by_rating: "Filter by rating",
  admin_feedback_filter_all: "All",
  admin_feedback_filter_n_stars: "{count} Stars",
  admin_no_feedback_found: "No feedback has been submitted yet.",
  admin_no_feedback_match: "No feedback matches the selected filter.",
  admin_stats_total_users: "Total Users",
  admin_stats_admins: "Admins",
  admin_stats_premium_users: "Premium Users",
  admin_stats_doctors: "Doctors",
  admin_stats_hr_admins: "HR Admins",
  admin_stats_normal_users: "Normal Users",
  admin_stats_total_evaluations: "Total Evaluations",
  admin_stats_loading: "Loading stats...",
  admin_stats_error: "Could not load statistics.",

  hr_admin_title: "HR Admin Panel",
  hr_admin_tab_dashboard: "Dashboard",
  hr_admin_tab_employees: "Employees",
  hr_admin_tab_teams: "Teams",
  hr_admin_dashboard_placeholder: "The dashboard with team stats, alerts, and evaluation tracking will be available soon.",
  hr_admin_employees_title: "Manage Employees",
  hr_admin_add_employee: "Add Employee",
  hr_admin_no_employees: "No employees have been added yet.",
  hr_admin_teams_title: "Manage Teams",
  hr_admin_add_team: "Add Team",
  hr_admin_no_teams: "No teams have been created yet.",
  hr_admin_team_unassigned: "Unassigned",
  hr_modal_employee_title_add: "Add New Employee",
  hr_modal_employee_title_edit: "Edit Employee",
  hr_modal_team_title_add: "Add New Team",
  hr_modal_team_title_edit: "Edit Team",
  hr_field_firstName: "First Name",
  hr_field_lastName: "Last Name",
  hr_field_email: "Email",
  hr_field_team: "Team",
  hr_field_no_team: "No Team",
  hr_field_team_name: "Team Name",
  hr_button_save: "Save",
  hr_button_saving: "Saving...",
  hr_button_cancel: "Cancel",
  hr_button_edit: "Edit",
  hr_table_header_name: "Name",
  hr_table_header_email: "Email",
  hr_table_header_team: "Team",
  hr_table_header_last_check: "Last Check",
  hr_table_header_actions: "Actions",
  hr_dashboard_total_members: "Total Team Members",
  hr_dashboard_evaluations_pending: "Pending 1st Eval",
  hr_dashboard_evaluations_due_soon: "Due Soon",
  hr_dashboard_evaluations_overdue: "Overdue",
  hr_dashboard_team_members_title: "Team Member Status",
  hr_dashboard_table_header_member: "Member",
  hr_dashboard_table_header_last_eval: "Last Evaluation",
  hr_dashboard_table_header_next_eval: "Next Evaluation",
  hr_dashboard_table_header_status: "Status",
  hr_dashboard_status_ok: "OK",
  hr_dashboard_status_due_soon: "Due Soon",
  hr_dashboard_status_overdue: "Overdue",
  hr_dashboard_status_pending: "Pending",
  hr_dashboard_no_eval_history: "No history",
  hr_dashboard_loading_data: "Loading dashboard data...",

  pagination_previous: "Previous",
  pagination_next: "Next",
  pagination_page_info: "Page {currentPage} of {totalPages}",
  
  doctor_portal_title: "Doctor Portal",
  doctor_portal_loading: "Loading patient evaluations...",
  doctor_portal_error: "Could not load evaluations. Please try again later.",
  doctor_portal_no_evals: "No patient evaluations found.",
  doctor_portal_table_patient: "Patient",
  doctor_portal_table_date: "Date",
  doctor_portal_table_status: "Status",
  doctor_portal_table_action: "Action",
  doctor_portal_review_button: "Review",
  doctor_portal_view_button: "View",
  doctor_portal_back_button: "Back to Portal",
  doctor_portal_status_pending: "Pending Review",
  doctor_portal_status_responded: "Responded",
  doctor_portal_search_placeholder: "Search by patient name...",
  doctor_portal_no_match: "No evaluations match your search.",

  evaluation_detail_title: "Review Evaluation",
  evaluation_detail_add_note: "Add Doctor's Note",
  evaluation_detail_note_placeholder: "Enter your professional diagnosis or comments here...",
  evaluation_detail_add_button: "Add Note",
  evaluation_detail_adding_note: "Adding note...",
  evaluation_detail_previous_notes: "Previous Notes",
  evaluation_detail_no_notes: "No notes have been added to this evaluation yet.",
  evaluation_detail_error: "Could not add note. Please try again.",
  evaluation_detail_your_note_title: "Your Submitted Note",
  evaluation_detail_note_submitted_on: "Submitted on",
  
  language_switcher_en: "EN",
  language_switcher_es: "ES",

  support_title: "Support & Help",
  support_heading: "Need Assistance?",
  support_intro: "We're sorry you're experiencing an issue. Our team is here to help.",
  support_instruction_email: "To resolve your issue as quickly as possible, please send us an email at:",
  support_instruction_include: "Please be sure to include the following information:",
  support_info_1: "The email address you used to sign up.",
  support_info_2: "The approximate date and time of the transaction.",
  support_info_3: "A brief description of the problem you experienced.",
  support_backToHomeButton: "Back to Home Page",
  
  footer_supportLink: "Support",

  report_confidential_title: "Confidential Eye Health Report",
  report_date_generated: "Date Generated",
  report_patient_info: "Patient Information",
  report_patient_name: "Name",
  report_patient_dob: "Date of Birth",
  report_patient_email: "Email",
  report_ai_summary_title: "AI-Powered Summary",
  report_questionnaire_summary: "Questionnaire Summary",
  report_image_analysis_details: "Image Analysis Details",
  report_submitted_image: "Submitted Image",
  report_no_findings: "The initial image analysis did not detect any immediate signs of major conditions based on the provided image.",
  report_nearby_ophthalmologists: "Nearby Ophthalmologists",
  report_phone: "Phone",
  report_doctor_notes_title: "Doctor's Notes",
  questionnaire_reason: "Reason for evaluation",
  questionnaire_lenses: "Wears lenses",
  questionnaire_satisfactionLabel: "Satisfaction",
  questionnaire_lastUpdateLabel: "Last update",
  questionnaire_surgery: "Had surgery/injury",
  questionnaire_surgeryOrInjuryDetails: "Details",
  questionnaire_illnesses: "General illnesses",
  questionnaire_familyHistory: "Family eye history",
  questionnaire_symptoms: "Current symptoms",
  questionnaire_not_answered: "Not answered",
  date_locale: "en-US",

  // Generic
  error_generic_api_key_missing: "AI service is unavailable: API Key is missing. Please contact support.",
  error_generic_api_key_invalid: "AI service is unavailable: The configured API key is invalid. Please contact support.",
  error_generic_api_fetch_failed: "Failed to fetch tips due to an API error: {errorMessage}",
  error_generic_unexpected_api: "An unexpected error occurred while communicating with the AI service. Please try again.",
  error_generic_api_timeout: "The AI service took too long to respond. Please try again.",
  error_image_processing: "Could not process the image. Please try again.",
  error_generic_no_tips_received: "No tips received from the AI. Please try again later.",
  error_analysis_blocked: "Analysis could not be completed because the submitted image was unclear or inappropriate. Please try again with a clear photo of just your eye.",
  
  report_download_pdf_button: "Download PDF Report",
  report_downloading_pdf: "Downloading...",
  feedback_button: "Give Feedback",
  feedback_submitted: "Feedback Submitted",
  feedback_thanks_title: "Thank You!",
  feedback_thanks_message: "Your feedback has been submitted successfully.",
  feedback_title: "Rate Your Experience",
  feedback_subtitle: "Your opinion helps us improve.",
  feedback_comment_placeholder: "Leave an optional comment...",
  feedback_close_button: "Close",
  feedback_submit_button: "Submit Feedback",
};

export type TranslationKeys = typeof en;
