import { TranslationKeys } from './en';

export const es: TranslationKeys = {
  appName: "Niria",
  appMotto: "El futuro del cuidado ocular comienza con una foto.",
  appSubMotto: "Obtenga información rápida sobre la salud de sus ojos, impulsada por IA, desde la comodidad de su hogar.",
  footerText: "© TREASURES OF ZIMA LLC.",
  footerDisclaimer: "Niria es una herramienta informativa y no proporciona asesoramiento médico.",
  resultsDisclaimerShort: "No es consejo médico. Consulte a un doctor.",
  resultsDisclaimer: "Importante: El análisis proporcionado por Niria es solo para fines informativos y no sustituye un diagnóstico médico profesional. Consulte siempre a un oftalmólogo calificado o proveedor de atención médica para cualquier inquietud sobre la salud ocular o antes de tomar decisiones relacionadas con su salud o tratamiento.",
  paymentPlaceholderText: "Nuestro portal de pago seguro estará disponible próximamente. En una aplicación real, esta página se integraría con un procesador de pagos como Stripe o PayPal para manejar las transacciones de forma segura.",

  home_ctaButton: "Iniciar Análisis",
  home_whyChooseNiria: "¿Por Qué Elegir Niria?",
  home_mission_title: "Nuestra Misión",
  home_mission_text: "Brindar una app intuitiva, accesible y asequible que use inteligencia artificial para identificar señales tempranas en la salud visual y guiar a las personas hacia especialistas cercanos, promoviendo la prevención como un acto de cuidado y autonomía personal.",
  home_vision_title: "Nuestra Visión",
  home_vision_text: "Que cualquier persona en el mundo, sin importar su ubicación, pueda recibir una orientación temprana sobre su salud visual a través de una herramienta confiable, accesible y cercana.",
  home_fact_title: "¿Sabías que...?",
  home_fact1: "Al menos 2.200 millones de personas padecen alguna afección visual, y alrededor de 1.000 millones podrían haberse evitado o no se han abordado aún con atención adecuada.",
  home_fact2: "Los principales factores globales de pérdida visual son errores refractivos no corregidos (≈42%) y cataratas (≈33%), ambos tratables con intervenciones simples.",
  home_fact3: "La retinopatía diabética, común en personas con diabetes, puede prevenir la ceguera en al menos el 90% de los casos con diagnóstico y tratamiento oportunos.",
  home_fact4: "Afecciones como cataratas, glaucoma y AMD elevan el riesgo de caídas en adultos mayores hasta en un 38%.",
  home_testimonials_title: "Historias que Inspiran Confianza",

  feature_resultsInMinutes_title: "Resultados en Minutos",
  feature_resultsInMinutes_description: "Recibe una orientación preliminar y cuidadosa. Nuestra IA analiza tu foto en instantes para ofrecerte claridad y tranquilidad de forma oportuna.",
  feature_noExpensiveEquipment_title: "Sin Equipos Costosos",
  feature_noExpensiveEquipment_description: "No necesitas equipos especiales. Tu propio smartphone es la única herramienta que necesitas para dar el primer paso y cuidar tu salud visual.",
  feature_highAccuracyPotential_title: "Potencial de Alta Precisión",
  feature_highAccuracyPotential_description: "Nuestro servicio utiliza IA avanzada para reconocer patrones visuales con cuidado, brindándote una orientación inicial confiable.",
  feature_securePrivate_title: "Seguro y Privado",
  feature_securePrivate_description: "Tu confianza es primordial. Tus fotos y datos son tratados con los más altos estándares de privacidad y seguridad, siempre.",

  testimonial1_quote: "Viviendo lejos de mi mamá, siempre me preocupaba su salud. Quejarse de su visión me hacía sentir impotente. Niria fue un cambio total. Fue tan fácil de usar para ella, y la alerta suave nos dio la claridad que necesitábamos para ver a un especialista cercano. Es más que una app; es tranquilidad.",
  testimonial1_name: "Laura G.",
  testimonial1_role: "La Hija Preocupada",
  testimonial2_quote: "Como desarrollador, mis ojos son mi herramienta más importante. El tiempo constante frente a la pantalla me causaba fatiga y quería una forma rápida de revisar mi salud visual sin una cita completa. Niria es brillante: rápido, directo y los resultados se presentaron con claridad. Me dio los datos que necesitaba para ser proactivo.",
  testimonial2_name: "Daniel K.",
  testimonial2_role: "El Tecnológico que se Cuida",
  testimonial3_quote: "Mantener mi independencia lo es todo para mí. Buscaba una forma sencilla de vigilar mi visión sin aparatos complicados. Niria es maravillosamente simple. Las instrucciones son claras y el informe fue fácil de entender y compartir con mi hija. Es una herramienta reconfortante tenerla.",
  testimonial3_name: "Margarita P.",
  testimonial3_role: "La Adulta Mayor Conectada",

  auth_loginToAccount: "Inicia Sesión en Tu Cuenta",
  auth_createAccount: "Crear una Cuenta",
  auth_firstNameLabel: "Nombre",
  auth_firstNamePlaceholder: "Juana",
  auth_lastNameLabel: "Apellido",
  auth_lastNamePlaceholder: "Pérez",
  auth_emailLabel: "Correo Electrónico",
  auth_emailPlaceholder: "usted@ejemplo.com",
  auth_passwordLabel: "Contraseña",
  auth_signInButton: "Iniciar Sesión",
  auth_signUpButton: "Crear Cuenta",
  auth_googleSignInButton: "Iniciar sesión con Google",
  auth_loggingInButton: "Iniciando sesión...",
  auth_registeringButton: "Creando cuenta...",
  auth_dontHaveAccount: "¿No tienes una cuenta?",
  auth_signUpHereLink: "Regístrate",
  auth_alreadyHaveAccount: "¿Ya tienes una cuenta?",
  auth_signInHereLink: "Inicia Sesión",
  auth_orDivider: "O",
  auth_areYouADoctor: "¿Eres un profesional médico?",
  auth_registerAsDoctorLink: "Regístrate aquí.",
  auth_doctorRegistrationTitle: "Registro para Profesionales Médicos",
  auth_not_a_doctor: "¿No eres doctor?",
  auth_register_as_user_link: "Regístrate como usuario.",
  auth_doctor_signup_success: "¡Registro exitoso! Tu solicitud ha sido enviada para aprobación del administrador.",
  
  doctor_specialty_label: "Especialidad",
  doctor_specialty_placeholder: "Ej: Oftalmología",
  doctor_license_label: "Número de Licencia Médica",
  doctor_license_placeholder: "Ej: 123456789",
  doctor_graduationYear_label: "Año de Graduación",
  doctor_graduationYear_placeholder: "Ej: 2010",
  doctor_country_label: "País",
  doctor_country_placeholder: "Ej: México",
  doctor_state_label: "Estado/Provincia",
  doctor_state_placeholder: "Ej: Jalisco",
  doctor_city_label: "Ciudad",
  doctor_city_placeholder: "Ej: Guadalajara",

  auth_forgot_password_link: "¿Olvidaste tu contraseña?",
  auth_reset_password_title: "Restablecer Contraseña",
  auth_reset_password_instructions: "Ingresa el correo electrónico asociado con tu cuenta y te enviaremos un enlace para restablecer tu contraseña.",
  auth_send_link_button: "Enviar Enlace de Restablecimiento",
  auth_sending_link_button: "Enviando Enlace...",
  auth_back_to_signin_link: "← Volver a Iniciar Sesión",
  auth_reset_link_sent: "¡Enlace de restablecimiento enviado! Por favor, revisa tu bandeja de entrada y la carpeta de spam.",
  auth_error_passwordsDoNotMatch: "Las contraseñas no coinciden.",
  auth_error_loginFailed: "Falló el inicio de sesión. Por favor verifique sus credenciales.",
  auth_error_registrationFailed: "Falló el registro. Por favor inténtelo de nuevo.",
  auth_error_unexpected: "Ocurrió un error inesperado. Por favor, inténtelo de nuevo.",
  auth_error_email_in_use: "Esta dirección de correo electrónico ya está en uso por otra cuenta.",
  auth_error_weak_password: "La contraseña es demasiado débil. Debe tener al menos 6 caracteres.",
  auth_error_user_not_found: "No se encontró ninguna cuenta con esta dirección de correo electrónico.",
  auth_error_invalid_credentials: "Correo electrónico o contraseña incorrectos. Por favor, verifique sus credenciales o intente restablecer su contraseña.",
  auth_error_invalid_email: "La dirección de correo electrónico no es válida.",

  exam_title: "Análisis de Salud Ocular",
  exam_instructions: "Para mejores resultados, asegúrese de que su ojo esté bien iluminado y enfocado. Quítese las gafas o lentes de contacto si es posible. La imagen debe mostrar claramente su iris y pupila.",
  exam_uploadPhotoButton: "Subir Foto",
  exam_stopCameraButton: "Detener Cámara",
  exam_takePhotoWithCameraButton: "Tomar Foto con Cámara",
  exam_capturePhotoButton: "Capturar Foto",
  exam_imagePreviewTitle: "Vista Previa de Imagen:",
  exam_livePreviewTitle: "Vista Previa de la Cámara en Vivo",
  exam_analyzeButton: "Analizar Foto del Ojo",
  exam_analyzingText: "Analizando su foto...",
  exam_error_fileTooLarge: "El archivo es demasiado grande. El tamaño máximo es 10MB.",
  exam_error_invalidFileType: "Tipo de archivo inválido. Por favor suba una imagen JPG, PNG, o WEBP.",
  exam_error_noPhoto: "Por favor suba o tome una foto de su ojo primero.",
  exam_error_cameraAccess: "No se pudo acceder a la cámara. Por favor asegúrese de que los permisos están concedidos.",
  exam_error_cameraNotSupported: "La cámara no es compatible con este navegador.",
  exam_error_analysisFailed: "Ocurrió un error durante el análisis. Por favor, compruebe su conexión e inténtelo de nuevo.",
  exam_error_missingData: "Faltan los datos del usuario o el cuestionario de salud. Por favor, reinicie el proceso desde la página de inicio.",
  exam_error_invalid_image_data: "Los datos de la imagen proporcionada no son válidos. Vuelva a intentar capturar o subir la foto.",
  exam_retakePhotoButton: "Volver a Tomar",
  exam_cancelButton: "Cancelar",
  exam_processing_image: "Procesando imagen...",
  exam_instructions_title: "Instrucciones para capturar la imagen de ambos ojos",
  exam_instructions_step1: "Limpie el lente de la cámara antes de comenzar.",
  exam_instructions_step2: "Ubíquese en un lugar bien iluminado, preferiblemente cerca de una ventana.",
  exam_instructions_step3: "Evite la luz solar directa y no utilice flash.",
  exam_instructions_step4: "Abra ambos ojos lo máximo posible y mire directamente a la cámara.",
  exam_instructions_step5: "Si es posible, solicite la asistencia de otra persona para asegurar que ambos ojos estén centrados y visibles en la imagen.",
  exam_instructional_video_aria: "Video instructivo de captura ocular",
  exam_mask_instruction: "Alinee sus ojos dentro de los óvalos para obtener los mejores resultados.",

  consent_title: "Consentimiento Informado para la Recopilación de Datos",
  consent_intro: "Antes de continuar, por favor lea y acepte los siguientes términos sobre la recopilación y uso de sus datos.",
  consent_purpose_title: "Propósito de la Recopilación de Datos",
  consent_purpose_text: "Recopilaremos información personal y médica a través del cuestionario de salud y la foto de su ojo que proporcione. Estos datos son esenciales para que nuestra IA realice un análisis preliminar de su salud ocular.",
  consent_confidentiality_title: "Confidencialidad y Seguridad",
  consent_confidentiality_text: "Su información se almacenará de forma segura y se manejará con la más estricta confidencialidad. Solo se utilizará para el propósito de este análisis y para mejorar nuestros servicios. No vendemos sus datos personales.",
  consent_not_a_diagnosis_title: "No es un Diagnóstico Médico",
  consent_not_a_diagnosis_text: "Este análisis es una herramienta informativa, no un sustituto de un diagnóstico médico profesional. Consulte siempre a un proveedor de atención médica calificado para cualquier problema de salud.",
  consent_acceptance_text: "Al hacer clic en 'Aceptar y Continuar', usted confirma que ha leído, entendido y acepta la recopilación y uso de sus datos como se describe anteriormente.",
  consent_accept_button: "Aceptar y Continuar",
  consent_decline_button: "Rechazar",
  consent_declined_title: "Se Requiere Consentimiento",
  consent_declined_message: "Debe aceptar los términos para proceder con el análisis de salud ocular. Puede reiniciar el proceso desde la página de inicio si cambia de opinión.",

  questionnaire_title: "Cuestionario de Salud del Paciente",
  questionnaire_intro: "Por favor, responda las siguientes preguntas para proporcionar contexto para su análisis.",
  questionnaire_submitButton: "Continuar a la Captura de Foto",
  questionnaire_next_button: "Siguiente",
  questionnaire_previous_button: "Anterior",
  questionnaire_progress_step: "Paso {current} de {total}",

  q_option_other_not_sure: "Otro / No estoy seguro",
  
  q_firstNameLabel: "Nombre",
  q_firstNamePlaceholder: "Juana",
  q_lastNameLabel: "Apellido",
  q_lastNamePlaceholder: "Pérez",
  q_cityLabel: "Ciudad",
  q_cityPlaceholder: "Ej: Nueva York",
  q_stateLabel: "Estado",
  q_statePlaceholder: "Ej: NY",
  q_dob_label: "Fecha de Nacimiento",
  q_dob_day_placeholder: "Día",
  q_dob_month_placeholder: "Mes",
  q_dob_year_placeholder: "Año",
  month_january: "Enero",
  month_february: "Febrero",
  month_march: "Marzo",
  month_april: "Abril",
  month_may: "Mayo",
  month_june: "Junio",
  month_july: "Julio",
  month_august: "Agosto",
  month_september: "Septiembre",
  month_october: "Octubre",
  month_november: "Noviembre",
  month_december: "Diciembre",

  q1_label_new: "1. ¿Cuál es el motivo para realizar esta evaluación?",
  q1_option_blurry: "Visión borrosa o alterada",
  q1_option_tired: "Ojos cansados o fatigados",
  q1_option_redness: "Enrojecimiento o irritación",
  q1_option_checkup: "Chequeo periódico",

  q2_label: "2. ¿Usa lentes (gafas o lentes de contacto)?",
  q2_yes: "Sí",
  q2_no: "No",
  q2_other: "Otro / No estoy seguro",
  q2_satisfactionLabel: "Si es así, ¿qué tan satisfecho está con ellos?",
  q2_satisfactionPlaceholder: "Ej: Funcionan bien, me dan dolores de cabeza...",
  q2_lastUpdateLabel: "¿Cuándo fue la última vez que actualizó su prescripción?",
  q2_lastUpdatePlaceholder: "Ej: Hace 6 meses, hace más de 2 años...",
  q3_label: "3. ¿Ha tenido alguna vez una cirugía ocular, una lesión o trauma importante, o una infección ocular grave?",
  q3_detailsLabel: "Si es así, por favor proporcione detalles.",
  q3_detailsPlaceholder: "Ej: LASIK en 2018, rasguño corneal...",
  q4_label: "4. ¿Tiene alguna enfermedad general importante?",
  q4_illness_diabetes: "Diabetes",
  q4_illness_highBloodPressure: "Presión arterial alta",
  q4_illness_highCholesterol: "Colesterol alto",
  q4_illness_thyroid: "Enfermedad de la tiroides",
  q4_illness_arthritis: "Artritis",
  q5_label: "5. ¿Alguien en su familia inmediata (padres, abuelos, hermanos) tiene alguna condición ocular significativa?",
  q5_condition_glaucoma: "Glaucoma",
  q5_condition_macularDegeneration: "Degeneración macular",
  q5_condition_strabismus: "Estrabismo",
  q5_condition_highMyopia: "Miopía alta",
  q6_label: "6. Además de su queja principal, ¿ha experimentado alguno de los siguientes síntomas?",
  q6_symptom_pain: "Dolor",
  q6_symptom_itching: "Picazón",
  q6_symptom_burning: "Ardor",
  q6_symptom_tearing: "Lagrimeo excesivo",
  q6_symptom_gritty: "Sensación de arenilla",
  q6_symptom_lightSensitivity: "Sensibilidad a la luz",
  q6_symptom_doubleVision: "Visión doble",
  q6_symptom_none: "Ninguno de los anteriores",

  q_screenTime_label: "7. En promedio, ¿cuántas horas al día pasa frente a una computadora o pantalla digital?",
  q_screenTime_placeholder: "Seleccione una opción",
  q_screenTime_option_0_2: "Menos de 2 horas",
  q_screenTime_option_2_4: "2-4 horas",
  q_screenTime_option_4_8: "4-8 horas",
  q_screenTime_option_8_plus: "Más de 8 horas",

  error_validation_name: "Por favor, ingrese su nombre y apellido.",
  error_validation_dob_full: "Por favor, seleccione su fecha de nacimiento completa (día, mes y año).",
  error_validation_state: "Por favor, seleccione un estado.",

  results_title: "Su Análisis de Salud Ocular",
  results_summaryTitle: "Resumen Impulsado por IA",
  results_detailedFindingsTitle: "Hallazgos Detallados del Análisis de Imagen",
  results_noResults: "No hay resultados de análisis para mostrar.",
  results_riskLevelSuffix: "Riesgo",
  results_importantDisclaimerTitle: "Descargo de Responsabilidad Importante",
  results_generalEyeHealthTipsTitle: "Consejos Generales de Salud Ocular",
  results_fetchingTips: "Obteniendo consejos...",
  results_error_couldNotLoadTips: "No se pudieron cargar los consejos de salud ocular en este momento. Por favor, inténtelo de nuevo más tarde.",
  results_refreshTipsButton: "Actualizar Consejos",
  results_proceedToPaymentButton: "Proceder al Pago",
  results_performAnotherAnalysisButton: "Realizar Otro Análisis",
  results_backToHomeButton: "Volver al Inicio",
  results_loadingSummary: "Cargando resumen...",
  results_error_loading: "No pudimos cargar sus resultados. Si ya ha pagado, por favor",
  results_download_for_details: "Para un desglose detallado de su cuestionario, análisis de imagen y una lista de especialistas locales, por favor descargue el informe completo en PDF.",

  results_condition_cataract: "Desarrollo de Cataratas",
  results_details_cataract: "Se observó una ligera opacidad del cristalino, se recomienda seguimiento.",
  results_condition_glaucomaIndicators: "Indicadores de Glaucoma",
  results_details_glaucomaIndicators: "Signos visuales que pueden estar asociados con glaucoma, como cambios en el nervio óptico o el iris.",
  results_condition_ptosis: "Ptosis (Párpado Caído)",
  results_details_ptosis: "El párpado superior está más bajo de lo normal, lo que puede afectar la visión.",
  results_condition_subconjunctivalHemorrhage: "Hemorragia Subconjuntival",
  results_details_subconjunctivalHemorrhage: "Un vaso sanguíneo roto en la superficie del ojo, a menudo inofensivo pero debe ser revisado.",
  results_condition_conjunctivitis: "Infección / Conjuntivitis",
  results_details_conjunctivitis: "Signos de inflamación o infección de la conjuntiva (conjunctivitis), como enrojecimiento y secreción.",
  results_condition_abnormalPupils: "Pupilas Anormales",
  results_details_abnormalPupils: "Las pupilas parecen de tamaño desigual, deformes o tienen un color inusual, lo que requiere evaluación médica.",
  results_condition_ocularJaundice: "Ictericia Ocular",
  results_details_ocularJaundice: "Coloración amarillenta de la parte blanca del ojo, que puede indicar problemas hepáticos.",
  results_condition_cornealArcus: "Arco Corneal",
  results_details_cornealArcus: "Un anillo blanco, gris o azul alrededor de la córnea, a veces asociado con colesterol alto.",
  results_condition_inflammation: "Inflamación / Enrojecimiento",
  results_details_inflammation: "Se detectaron signos generales de inflamación, enrojecimiento significativo o secreción.",
  results_condition_drynessOrTearing: "Sequedad / Lagrimeo Anormal",
  results_details_drynessOrTearing: "Signos visuales que pueden indicar problemas con la producción de lágrimas, como sequedad o lagrimeo excesivo.",

  results_risk_low: "Bajo",
  results_risk_medium: "Medio",
  results_risk_high: "Alto",
  results_risk_undetermined: "Indeterminado",
  
  payment_title: "Pago Seguro",
  payment_unlock_title: "Desbloquee su Informe Completo",
  payment_unlock_description: "Por un pago único, obtenga un PDF descargable de su análisis detallado y guárdelo para sus registros.",
  payment_pay_now_button: "Pagar $10.00 Ahora",
  payment_processing: "Procesando...",
  payment_support_prompt: "¿Problemas con tu pago?",
  payment_support_link: "Contacta a Soporte",

  header_welcomeMessage: "Bienvenido, {email}",
  header_logoutButton: "Cerrar Sesión",
  header_loginRegisterButton: "Iniciar Sesión / Registrarse",
  header_myProfileLink: "Mi Perfil",
  header_adminPanel: "Panel de Admin",
  header_doctorPortal: "Portal de Doctores",
  header_hrAdminPanel: "Panel de RRHH",
  header_pricingLink: "Precios",

  profile_title: "Mi Perfil",
  profile_personal_info_title: "Información Personal",
  profile_medical_info_title: "Información Médica",
  profile_reminders_title: "Mis Recordatorios",
  profile_history_title: "Historial de Evaluaciones",
  profile_tab_personal_info: "Info Personal",
  profile_tab_consultation: "Consulta y Recordatorios",
  history_evaluationDate: "Fecha de Evaluación",
  profile_noHistory: "No tienes evaluaciones pasadas.",
  profile_loading: "Cargando tu perfil...",
  profile_fetchError: "No se pudo cargar tu perfil. Por favor, inténtalo de nuevo más tarde.",
  profile_doctor_note_title: "Nota del Doctor",
  profile_edit_button: "Editar Perfil",
  profile_save_button: "Guardar Cambios",
  profile_saving_button: "Guardando...",
  profile_cancel_button: "Cancelar",
  profile_change_photo_button: "Cambiar Foto",
  profile_change_photo_prompt: "Haz clic abajo para subir una nueva foto de perfil.",
  profile_uploading_photo: "Subiendo...",
  profile_error_upload: "Error al subir la foto.",
  profile_error_save: "Error al guardar el perfil.",
  profile_label_phone: "Número de Teléfono",
  profile_placeholder_phone: "(555) 123-4567",
  profile_label_allergies: "Alergias",
  profile_placeholder_allergies: "Ej: Polen, Penicilina",
  profile_label_conditions: "Condiciones Médicas",
  profile_placeholder_conditions: "Ej: Diabetes tipo 2",
  profile_label_surgeries: "Cirugías Anteriores",
  profile_placeholder_surgeries: "Ej: Extirpación de apéndice (2015)",
  profile_reminders_none: "No tienes recordatorios activos.",
  profile_reminders_add_new: "Añadir Recordatorio",

  reminder_modal_title_add: "Añadir Nuevo Recordatorio",
  reminder_modal_title_edit: "Editar Recordatorio",
  reminder_type: "Tipo de Recordatorio",
  reminder_type_medication: "Medicación",
  reminder_type_consultation: "Consulta",
  reminder_name_label: "Nombre / Título",
  reminder_name_placeholder_medication: "Ej: Gotas para ojos Latanoprost",
  reminder_name_placeholder_consultation: "Ej: Seguimiento con Dr. García",
  reminder_details_label: "Detalles / Dosis",
  reminder_details_placeholder_medication: "Ej: 1 gota en cada ojo",
  reminder_details_placeholder_consultation: "Ej: Chequeo de progreso de glaucoma",
  reminder_frequency_label: "Frecuencia",
  reminder_frequency_helper: "Recordarme cada...",
  reminder_frequency_hours: "Hora(s)",
  reminder_frequency_days: "Día(s)",
  reminder_frequency_weeks: "Semana(s)",
  reminder_frequency_months: "Mes(es)",
  reminder_starts_at_label: "Hora del Primer Recordatorio",
  reminder_save_button: "Guardar Recordatorio",
  reminder_delete_button: "Eliminar",
  reminder_next_due: "Próximo:",
  reminder_notification_permission_title: "Activar Notificaciones",
  reminder_notification_permission_body: "Para recibir recordatorios, por favor permite que Niria te envíe notificaciones.",
  reminder_notification_denied: "Las notificaciones están bloqueadas. Por favor, actívalas en la configuración de tu navegador para recibir recordatorios.",
  reminder_notification_medication_title: "Recordatorio de Medicación",
  reminder_notification_consultation_title: "Recordatorio de Consulta",

  admin_title: "Panel de Administración",
  admin_manageUsers: "Gestionar Usuarios",
  admin_error_load_users: "No se pudo cargar la lista de usuarios. Es posible que no tengas permiso.",
  admin_success_role_update: "Rol de usuario actualizado correctamente.",
  admin_error_role_update: "Ocurrió un error al cambiar el rol.",
  admin_error_self_remove: "No puedes eliminar tu propio estado de administrador.",
  admin_table_header_user: "Usuario",
  admin_table_header_role: "Rol",
  admin_table_header_action: "Acción",
  admin_role_admin: "Admin",
  admin_role_user: "Usuario",
  admin_role_premium: "Premium",
  admin_role_doctor: "Doctor",
  admin_role_hr_admin: "Admin RRHH",
  admin_no_name: "Sin Nombre",
  admin_action_remove: "Quitar Admin",
  admin_action_make: "Hacer Admin",
  admin_action_approve: "Aprobar",
  admin_action_make_premium: "Hacer Premium",
  admin_action_remove_premium: "Quitar Premium",
  admin_action_make_doctor: "Hacer Doctor",
  admin_action_remove_doctor: "Quitar Doctor",
  admin_action_make_hr_admin: "Hacer Admin RRHH",
  admin_action_remove_hr_admin: "Quitar Admin RRHH",
  admin_success_premium_update: "Estado premium actualizado correctamente.",
  admin_error_premium_update: "Ocurrió un error al cambiar el estado premium.",
  admin_tab_users: "Gestión de Usuarios",
  admin_tab_feedback: "Feedback",
  admin_tab_stats: "Dashboard",
  admin_tab_doctor_requests: "Solicitudes de Doctores",
  admin_doctor_requests_title: "Aprobaciones de Doctores Pendientes",
  admin_no_doctor_requests: "No hay solicitudes de doctores pendientes.",
  admin_feedback_title: "Feedback de Usuarios",
  admin_feedback_table_header_rating: "Calificación",
  admin_feedback_table_header_comment: "Comentario",
  admin_feedback_table_header_date: "Fecha",
  admin_search_placeholder: "Buscar por nombre o email...",
  admin_no_users_found: "No se encontraron usuarios.",
  admin_no_users_match: "Ningún usuario coincide con tu búsqueda.",
  admin_feedback_filter_by_rating: "Filtrar por calificación",
  admin_feedback_filter_all: "Todos",
  admin_feedback_filter_n_stars: "{count} Estrellas",
  admin_no_feedback_found: "Aún no se ha enviado ningún comentario.",
  admin_no_feedback_match: "Ningún comentario coincide con el filtro seleccionado.",
  admin_stats_total_users: "Usuarios Totales",
  admin_stats_admins: "Administradores",
  admin_stats_premium_users: "Usuarios Premium",
  admin_stats_doctors: "Doctores",
  admin_stats_hr_admins: "Admins RRHH",
  admin_stats_normal_users: "Usuarios Normales",
  admin_stats_total_evaluations: "Evaluaciones Totales",
  admin_stats_loading: "Cargando estadísticas...",
  admin_stats_error: "No se pudieron cargar las estadísticas.",
  
  hr_admin_title: "Panel de Administrador de RRHH",
  hr_admin_tab_dashboard: "Dashboard",
  hr_admin_tab_employees: "Empleados",
  hr_admin_tab_teams: "Equipos",
  hr_admin_dashboard_placeholder: "El panel con estadísticas de equipo, alertas y seguimiento de evaluaciones estará disponible pronto.",
  hr_admin_employees_title: "Gestionar Empleados",
  hr_admin_add_employee: "Añadir Empleado",
  hr_admin_no_employees: "Aún no se han añadido empleados.",
  hr_admin_teams_title: "Gestionar Equipos",
  hr_admin_add_team: "Añadir Equipo",
  hr_admin_no_teams: "Aún no se han creado equipos.",
  hr_admin_team_unassigned: "Sin asignar",
  hr_modal_employee_title_add: "Añadir Nuevo Empleado",
  hr_modal_employee_title_edit: "Editar Empleado",
  hr_modal_team_title_add: "Añadir Nuevo Equipo",
  hr_modal_team_title_edit: "Editar Equipo",
  hr_field_firstName: "Nombre",
  hr_field_lastName: "Apellido",
  hr_field_email: "Correo Electrónico",
  hr_field_team: "Equipo",
  hr_field_no_team: "Sin Equipo",
  hr_field_team_name: "Nombre del Equipo",
  hr_button_save: "Guardar",
  hr_button_saving: "Guardando...",
  hr_button_cancel: "Cancelar",
  hr_button_edit: "Editar",
  hr_table_header_name: "Nombre",
  hr_table_header_email: "Email",
  hr_table_header_team: "Equipo",
  hr_table_header_last_check: "Último Chequeo",
  hr_table_header_actions: "Acciones",

  hr_dashboard_total_members: "Total Miembros del Equipo",
  hr_dashboard_evaluations_pending: "Pendiente 1ra Eval",
  hr_dashboard_evaluations_due_soon: "Próximo Vencimiento",
  hr_dashboard_evaluations_overdue: "Vencido",
  hr_dashboard_team_members_title: "Estado de Miembros del Equipo",
  hr_dashboard_table_header_member: "Miembro",
  hr_dashboard_table_header_last_eval: "Última Evaluación",
  hr_dashboard_table_header_next_eval: "Próxima Evaluación",
  hr_dashboard_table_header_status: "Estado",
  hr_dashboard_status_ok: "OK",
  hr_dashboard_status_due_soon: "Próximo",
  hr_dashboard_status_overdue: "Vencido",
  hr_dashboard_status_pending: "Pendiente",
  hr_dashboard_no_eval_history: "Sin historial",
  hr_dashboard_loading_data: "Cargando datos del dashboard...",

  pagination_previous: "Anterior",
  pagination_next: "Siguiente",
  pagination_page_info: "Página {currentPage} de {totalPages}",

  doctor_portal_title: "Portal de Doctores",
  doctor_portal_loading: "Cargando evaluaciones de pacientes...",
  doctor_portal_error: "No se pudieron cargar las evaluaciones. Por favor, inténtelo de nuevo más tarde.",
  doctor_portal_no_evals: "No se encontraron evaluaciones de pacientes.",
  doctor_portal_table_patient: "Paciente",
  doctor_portal_table_date: "Fecha",
  doctor_portal_table_status: "Estado",
  doctor_portal_table_action: "Acción",
  doctor_portal_review_button: "Revisar",
  doctor_portal_view_button: "Ver",
  doctor_portal_back_button: "Volver al Portal",
  doctor_portal_status_pending: "Pendiente de Revisión",
  doctor_portal_status_responded: "Respondido",
  doctor_portal_search_placeholder: "Buscar por nombre de paciente...",
  doctor_portal_no_match: "Ninguna evaluación coincide con tu búsqueda.",

  evaluation_detail_title: "Revisar Evaluación",
  evaluation_detail_add_note: "Añadir Nota del Doctor",
  evaluation_detail_note_placeholder: "Ingrese su diagnóstico profesional o comentarios aquí...",
  evaluation_detail_add_button: "Añadir Nota",
  evaluation_detail_adding_note: "Añadiendo nota...",
  evaluation_detail_previous_notes: "Notas Anteriores",
  evaluation_detail_no_notes: "Aún no se han añadido notas a esta evaluación.",
  evaluation_detail_error: "No se pudo añadir la nota. Por favor, inténtelo de nuevo.",
  evaluation_detail_your_note_title: "Tu Nota Enviada",
  evaluation_detail_note_submitted_on: "Enviado el",

  language_switcher_en: "EN",
  language_switcher_es: "ES",

  support_title: "Soporte y Ayuda",
  support_heading: "¿Necesitas Ayuda?",
  support_intro: "Lamentamos que hayas tenido un problema. Nuestro equipo está aquí para ayudarte.",
  support_instruction_email: "Para resolver tu problema lo más rápido posible, por favor envíanos un correo a:",
  support_instruction_include: "Por favor, asegúrate de incluir la siguiente información:",
  support_info_1: "El correo electrónico que usaste para registrarte.",
  support_info_2: "La fecha y hora aproximada de la transacción.",
  support_info_3: "Una breve descripción del problema que experimentaste.",
  support_backToHomeButton: "Volver a la Página Principal",
  
  footer_supportLink: "Soporte",

  report_confidential_title: "Reporte Confidencial de Salud Ocular",
  report_date_generated: "Fecha de Generación",
  report_patient_info: "Información del Paciente",
  report_patient_name: "Nombre",
  report_patient_dob: "Fecha de Nacimiento",
  report_patient_email: "Correo Electrónico",
  report_ai_summary_title: "Resumen Impulsado por IA",
  report_questionnaire_summary: "Resumen del Cuestionario",
  report_image_analysis_details: "Detalles del Análisis de Imagen",
  report_submitted_image: "Imagen Enviada",
  report_no_findings: "El análisis de imagen inicial no detectó signos inmediatos de condiciones mayores basados en la imagen proporcionada.",
  report_nearby_ophthalmologists: "Oftalmólogos Cercanos",
  report_phone: "Teléfono",
  report_doctor_notes_title: "Notas del Doctor",
  questionnaire_reason: "Motivo de la evaluación",
  questionnaire_lenses: "Usa lentes",
  questionnaire_satisfactionLabel: "Satisfacción",
  questionnaire_lastUpdateLabel: "Última actualización",
  questionnaire_surgery: "Tuvo cirugía/lesión",
  questionnaire_surgeryOrInjuryDetails: "Detalles",
  questionnaire_illnesses: "Enfermedades generales",
  questionnaire_familyHistory: "Historial ocular familiar",
  questionnaire_symptoms: "Síntomas actuales",
  questionnaire_not_answered: "No respondido",
  date_locale: "es-ES",

  // Pricing Page
  pricing_title: "Elige tu Plan",
  pricing_subtitle: "Precios simples y transparentes para cada necesidad.",
  pricing_plan_individual_title: "Análisis Individual",
  pricing_plan_individual_price: "$3.99",
  pricing_plan_individual_frequency: "Pago único",
  pricing_plan_individual_feature1: "Análisis con IA",
  pricing_plan_individual_feature2: "Reporte en PDF descargable",
  pricing_plan_individual_feature3: "Lista de especialistas cercanos",
  pricing_cta_get_started: "Comenzar",
  pricing_plan_plus_title: "Paquete Bienestar",
  pricing_plan_plus_price: "$4.99",
  pricing_plan_plus_frequency: "Pago único",
  pricing_plan_plus_feature1: "Todo lo del plan Individual",
  pricing_plan_plus_feature2: "Incluye 2 evaluaciones",
  pricing_cta_choose_plus: "Elegir Paquete",
  pricing_plan_business_title: "Niria para Empresas",
  pricing_plan_business_price: "Personalizado",
  pricing_plan_business_frequency: "Facturación Anual",
  pricing_plan_business_feature1: "Evaluaciones masivas para empleados",
  pricing_plan_business_feature2: "Panel de Administrador de RRHH",
  pricing_plan_business_feature3: "Seguimiento de bienestar de empleados",
  pricing_plan_business_feature4: "Soporte prioritario",
  pricing_cta_contact_sales: "Contactar a Ventas",
  pricing_best_value: "Mejor Valor",


  // Generic
  error_generic_api_key_missing: "El servicio de IA no está disponible: Falta la clave de API. Por favor, contacte al soporte.",
  error_generic_api_key_invalid: "El servicio de IA no está disponible: La clave de API configurada no es válida. Por favor, contacte al soporte.",
  error_generic_api_fetch_failed: "Error al obtener consejos debido a un error de API: {errorMessage}",
  error_generic_unexpected_api: "Ocurrió un error inesperado al comunicarse con el servicio de IA. Por favor, inténtelo de nuevo.",
  error_generic_api_timeout: "El servicio de IA tardó demasiado en responder. Inténtelo de nuevo.",
  error_image_processing: "No se pudo procesar la imagen. Inténtelo de nuevo.",
  error_generic_no_tips_received: "No se recibieron consejos de la IA. Por favor, inténtelo de nuevo más tarde.",
  error_analysis_blocked: "El análisis no se pudo completar porque la imagen enviada no era clara o era inapropiada. Por favor, inténtelo de nuevo con una foto clara de solo su ojo.",
  
  report_download_pdf_button: "Descargar Reporte PDF",
  report_downloading_pdf: "Descargando...",
  feedback_button: "Dar Feedback",
  feedback_submitted: "Feedback Enviado",
  feedback_thanks_title: "¡Gracias!",
  feedback_thanks_message: "Tu opinión ha sido enviada con éxito.",
  feedback_title: "Valora tu Experiencia",
  feedback_subtitle: "Tu opinión nos ayuda a mejorar.",
  feedback_comment_placeholder: "Deja un comentario (opcional)...",
  feedback_close_button: "Cerrar",
  feedback_submit_button: "Enviar Feedback",
};