import { TranslationKeys } from './en';

export const zh: TranslationKeys = {
  appName: "Niria",
  appMotto: "眼部护理的未来，从一张照片开始。",
  appSubMotto: "在舒适的家中，通过人工智能快速了解您的眼部健康状况。",
  footerText: "© TREASURES OF ZIMA LLC.",
  footerDisclaimer: "Niria 是一款信息工具，不提供医疗建议。",
  resultsDisclaimerShort: "非医疗建议。请咨询医生。",
  resultsDisclaimer: "重要提示：Niria 提供的分析仅供参考，不能替代专业的医疗诊断。如有任何眼部健康问题或在做出任何与您的健康或治疗相关的决定之前，请务必咨询合格的眼科医生或医疗保健提供者。",
  paymentPlaceholderText: "我们的安全支付门户即将推出。在实际应用中，此页面将与 Stripe 或 PayPal 等支付处理器集成，以安全处理交易。",

  home_ctaButton: "开始分析",
  home_ctaButton_free: "开始免费分析",
  home_whyChooseNiria: "为什么选择 Niria？",
  home_mission_title: "我们的使命",
  home_mission_text: "提供一款直观、易于访问且价格合理的应用程序，利用人工智能识别视觉健康的早期迹象，并引导人们找到附近的专家，将预防作为一种关怀和个人自主的行为加以推广。",
  home_vision_title: "我们的愿景",
  home_vision_text: "让世界上的任何人，无论身在何处，都能通过一个可靠、易于访问且平易近人的工具，获得关于其视觉健康的早期指导。",
  home_fact_title: "您知道吗...？",
  home_fact1: "全球至少有 22 亿人患有视力障碍，其中至少 10 亿人的视力障碍本可以预防或尚待解决。",
  home_fact2: "全球视力丧失的主要原因是未矫正的屈光不正（约 42%）和白内障（约 33%），这两种情况都可以通过简单的干预措施进行治疗。",
  home_fact3: "糖尿病视网膜病变在糖尿病患者中很常见，通过及时的诊断和治疗，至少 90% 的病例可以预防失明。",
  home_fact4: "白内障、青光眼和老年性黄斑变性等疾病会使老年人跌倒的风险增加高达 38%。",
  home_testimonials_title: "清晰与关怀的故事",

  feature_resultsInMinutes_title: "几分钟内获得结果",
  feature_resultsInMinutes_description: "获得关于您眼部健康的温和初步指导。我们的人工智能对您的照片进行快速分析，为您提供及时的清晰度。",
  feature_noExpensiveEquipment_title: "无需昂贵设备",
  feature_noExpensiveEquipment_description: "无需特殊硬件。您只需要一部智能手机，即可迈出了解您视觉健康的第一步。",
  feature_highAccuracyPotential_title: "高精度潜力",
  feature_highAccuracyPotential_description: "我们的服务由先进的人工智能提供支持，能够仔细识别视觉模式，为您提供可靠的初步见解。",
  feature_securePrivate_title: "安全与私密",
  feature_securePrivate_description: "您的信任就是一切。您的照片和数据将始终以最高的隐私和安全标准进行处理。",
  
  testimonial1_quote: "我住在离妈妈很远的地方，一直担心她的健康。她抱怨视力不好让我感到无助。Niria 改变了这一切。她用起来非常简单，温和的提醒让我们清楚地知道需要去看附近的专家。它不仅仅是一个应用程序，更是心灵的慰藉。",
  testimonial1_name: "劳拉·G",
  testimonial1_role: "42岁",
  testimonial2_quote: "作为一名开发人员，眼睛是我最重要的工具。长时间盯着屏幕导致眼睛疲劳，我想要一种快速检查视觉健康的方法，而不需要完整的预约。Niria 非常棒——快速、直接，结果清晰明了。它为我提供了主动采取行动所需的数据。",
  testimonial2_name: "丹尼尔·K",
  testimonial2_role: "31岁",
  testimonial3_quote: "保持独立对我来说就是一切。我一直在寻找一种简单的方法来关注我的视力，而不需要复杂的设备。Niria 非常简单直接。说明很清楚，报告很容易理解，还可以和我女儿分享。这是一个令人安心的工具。",
  testimonial3_name: "玛格丽特·P",
  testimonial3_role: "73岁",

  auth_loginToAccount: "登录您的帐户",
  auth_createAccount: "创建帐户",
  auth_firstNameLabel: "名字",
  auth_firstNamePlaceholder: "张",
  auth_lastNameLabel: "姓氏",
  auth_lastNamePlaceholder: "三",
  auth_emailLabel: "电子邮件地址",
  auth_emailPlaceholder: "you@example.com",
  auth_passwordLabel: "密码",
  auth_signInButton: "登录",
  auth_signUpButton: "创建帐户",
  auth_googleSignInButton: "使用 Google 登录",
  auth_loggingInButton: "正在登录...",
  auth_registeringButton: "正在创建帐户...",
  auth_dontHaveAccount: "没有帐户？",
  auth_signUpHereLink: "注册",
  auth_alreadyHaveAccount: "已有帐户？",
  auth_signInHereLink: "登录",
  auth_orDivider: "或",
  auth_areYouADoctor: "您是医疗专业人员吗？",
  auth_registerAsDoctorLink: "在此注册。",
  auth_doctorRegistrationTitle: "医疗专业人员注册",
  auth_not_a_doctor: "不是医生？",
  auth_register_as_user_link: "注册为用户。",
  auth_doctor_signup_success: "注册成功！您的请求已发送给管理员审批。",

  doctor_specialty_label: "专业",
  doctor_specialty_placeholder: "例如，眼科",
  doctor_license_label: "医疗执照号码",
  doctor_license_placeholder: "例如，123456789",
  doctor_graduationYear_label: "毕业年份",
  doctor_graduationYear_placeholder: "例如，2010",
  doctor_country_label: "国家",
  doctor_country_placeholder: "例如，美国",
  doctor_state_label: "州/省",
  doctor_state_placeholder: "例如，加利福尼亚州",
  doctor_city_label: "城市",
  doctor_city_placeholder: "例如，旧金山",

  auth_forgot_password_link: "忘记密码？",
  auth_reset_password_title: "重置密码",
  auth_reset_password_instructions: "输入与您的帐户关联的电子邮件地址，我们将向您发送一个重置密码的链接。",
  auth_send_link_button: "发送重置链接",
  auth_sending_link_button: "正在发送链接...",
  auth_back_to_signin_link: "← 返回登录",
  auth_reset_link_sent: "密码重置链接已成功发送。请检查您的收件箱和垃圾邮件文件夹。",
  auth_error_passwordsDoNotMatch: "密码不匹配。",
  auth_error_loginFailed: "登录失败。请检查您的凭据。",
  auth_error_registrationFailed: "注册失败。请重试。",
  auth_error_unexpected: "发生意外错误。请重试。",
  auth_error_email_in_use: "此电子邮件地址已被其他帐户使用。",
  auth_error_weak_password: "密码太弱。它应至少包含 6 个字符。",
  auth_error_user_not_found: "找不到使用此电子邮件地址的帐户。",
  auth_error_invalid_credentials: "电子邮件或密码不正确。请验证您的凭据或尝试重置密码。",
  auth_error_invalid_email: "电子邮件地址无效。",

  exam_title: "眼部健康分析",
  exam_instructions: "为获得最佳效果，请确保您的眼睛光线充足且对焦清晰。如果可能，请摘下眼镜或隐形眼镜。图像应清晰显示您的虹膜和瞳孔。",
  exam_uploadPhotoButton: "上传照片",
  exam_stopCameraButton: "停止相机",
  exam_takePhotoWithCameraButton: "用相机拍照",
  exam_capturePhotoButton: "拍照",
  exam_imagePreviewTitle: "图片预览：",
  exam_livePreviewTitle: "实时摄像头预览",
  exam_analyzeButton: "分析眼部照片",
  exam_analyzingText: "正在分析您的照片...",
  exam_error_fileTooLarge: "文件太大。最大大小为 10MB。",
  exam_error_invalidFileType: "文件类型无效。请上传 JPG、PNG 或 WEBP 图像。",
  exam_error_noPhoto: "请先上传或拍摄您的眼睛照片。",
  exam_error_cameraAccess: "无法访问摄像头。请确保已授予权限。",
  exam_error_cameraNotSupported: "此浏览器不支持摄像头。",
  exam_error_analysisFailed: "分析过程中发生错误。请检查您的网络连接并重试。",
  exam_error_missingData: "缺少用户数据或健康问卷。请从主页重新开始。",
  exam_error_invalid_image_data: "提供的图像数据无效。请尝试重新拍摄或上传照片。",
  exam_retakePhotoButton: "重新拍照",
  exam_cancelButton: "取消",
  exam_processing_image: "正在处理图像...",
  exam_instructions_title: "拍摄眼部图像说明",
  exam_instructions_step1: "开始前请清洁您的相机镜头。",
  exam_instructions_step2: "请在一个光线充足的地方，最好靠近窗户。",
  exam_instructions_step3: "避免阳光直射，不要使用闪光灯。",
  exam_instructions_step4: "尽可能睁大双眼，直视摄像头。",
  exam_instructions_step5: "如果可能，请寻求他人帮助，以确保双眼居中并清晰可见。",
  exam_instructional_video_aria: "眼部拍摄教学视频",
  exam_mask_instruction: "将您的眼睛对准椭圆框内以获得最佳效果。",
  exam_tips_title: "获得更好照片的提示：",
  exam_tip_lighting: "确保您的脸部光线充足，避免阴影。",
  exam_tip_no_backlight: "不要让明亮的光源（如窗户或太阳）在您身后。",
  exam_tip_clean_lens: "轻轻擦拭相机镜头以去除任何污迹。",

  consent_title: "数据收集知情同意书",
  consent_intro: "在继续之前，请阅读并接受以下有关数据收集和使用的条款。",
  consent_purpose_title: "数据收集目的",
  consent_purpose_text: "我们将通过健康问卷和您提供的眼部照片收集个人和医疗信息。这些数据对于我们的人工智能进行眼部健康初步分析至关重要。",
  consent_confidentiality_title: "保密与安全",
  consent_confidentiality_text: "您的信息将得到安全存储并严格保密。它将仅用于本次分析和改进我们的服务。我们不会出售您的个人数据。",
  consent_not_a_diagnosis_title: "非医疗诊断",
  consent_not_a_diagnosis_text: "此分析是一种信息工具，不能替代专业的医疗诊断。如有任何健康问题，请务必咨询合格的医疗保健提供者。",
  consent_acceptance_text: "点击“接受并继续”，即表示您已阅读、理解并同意按上述方式收集和使用您的数据。",
  consent_accept_button: "接受并继续",
  consent_decline_button: "我拒绝",
  consent_declined_title: "需要同意",
  consent_declined_message: "您必须接受条款才能进行眼部健康分析。如果您改变主意，可以从主页重新开始。",

  questionnaire_title: "患者健康问卷",
  questionnaire_intro: "请回答以下问题，为您的分析提供背景信息。",
  questionnaire_submitButton: "继续拍照",
  questionnaire_next_button: "下一步",
  questionnaire_previous_button: "上一步",
  questionnaire_progress_step: "第 {current} 步，共 {total} 步",
  
  q_option_other_not_sure: "其他/不确定",
  
  q_firstNameLabel: "名字",
  q_firstNamePlaceholder: "张",
  q_lastNameLabel: "姓氏",
  q_lastNamePlaceholder: "三",
  q_cityLabel: "城市",
  q_cityPlaceholder: "选择您的城市",
  q_stateLabel: "州",
  q_statePlaceholder: "选择您所在的州",
  q_dob_label: "出生日期",
  q_dob_day_placeholder: "日",
  q_dob_month_placeholder: "月",
  q_dob_year_placeholder: "年",
  month_january: "一月",
  month_february: "二月",
  month_march: "三月",
  month_april: "四月",
  month_may: "五月",
  month_june: "六月",
  month_july: "七月",
  month_august: "八月",
  month_september: "九月",
  month_october: "十月",
  month_november: "十一月",
  month_december: "十二月",

  q1_label_new: "1. 您进行此项评估的原因是什么？",
  q1_option_blurry: "视力模糊或改变",
  q1_option_tired: "眼睛疲劳或疲倦",
  q1_option_redness: "发红或刺激",
  q1_option_checkup: "定期检查",

  q2_label: "2. 您是否佩戴眼镜（眼镜或隐形眼镜）？",
  q2_yes: "是",
  q2_no: "否",
  q2_other: "其他/不确定",
  q2_satisfactionLabel: "如果是，您对它们的满意度如何？",
  q2_satisfactionPlaceholder: "例如，效果很好，我会头痛...",
  q2_lastUpdateLabel: "您上次更新处方是什么时候？",
  q2_lastUpdatePlaceholder: "例如，6 个月前，超过 2 年前...",
  q3_label: "3. 您是否曾接受过眼部手术、严重损伤或创伤，或严重的眼部感染？",
  q3_detailsLabel: "如果是，请提供详细信息。",
  q3_detailsPlaceholder: "例如，2018 年的 LASIK，角膜划伤...",
  q4_label: "4. 您是否有任何重大的全身性疾病？",
  q4_illness_diabetes: "糖尿病",
  q4_illness_highBloodPressure: "高血压",
  q4_illness_highCholesterol: "高胆固醇",
  q4_illness_thyroid: "甲状腺疾病",
  q4_illness_arthritis: "关节炎",
  q5_label: "5. 您的直系亲属中是否有人患有任何重大的眼部疾病？",
  q5_condition_glaucoma: "青光眼",
  q5_condition_macularDegeneration: "黄斑变性",
  q5_condition_strabismus: "斜视",
  q5_condition_highMyopia: "高度近视",
  q6_label: "6. 除了您的主要不适外，您是否经历过以下任何症状？",
  q6_symptom_pain: "疼痛",
  q6_symptom_itching: "瘙痒",
  q6_symptom_burning: "灼烧感",
  q6_symptom_tearing: "过度流泪",
  q6_symptom_gritty: "沙砾感",
  q6_symptom_lightSensitivity: "对光敏感",
  q6_symptom_doubleVision: "复视",
  q6_symptom_none: "以上均无",

  q_screenTime_label: "7. 平均每天您在电脑或数字屏幕前花费多少小时？",
  q_screenTime_placeholder: "选择一个选项",
  q_screenTime_option_0_2: "少于 2 小时",
  q_screenTime_option_2_4: "2-4 小时",
  q_screenTime_option_4_8: "4-8 小时",
  q_screenTime_option_8_plus: "超过 8 小时",
  
  error_validation_name: "请输入您的姓名。",
  error_validation_dob_full: "请选择您完整的出生日期（日、月、年）。",
  error_validation_state: "请选择一个州。",

  results_title: "您的眼部健康分析",
  results_summaryTitle: "人工智能摘要",
  results_detailedFindingsTitle: "图像分析详细结果",
  results_noResults: "没有可显示的分析结果。",
  results_riskLevelSuffix: "风险",
  results_importantDisclaimerTitle: "重要免责声明",
  results_generalEyeHealthTipsTitle: "一般眼部健康提示",
  results_fetchingTips: "正在获取提示...",
  results_error_couldNotLoadTips: "目前无法加载眼部健康提示。请稍后重试。",
  results_refreshTipsButton: "刷新提示",
  results_proceedToPaymentButton: "继续支付",
  results_performAnotherAnalysisButton: "进行另一次分析",
  results_backToHomeButton: "返回主页",
  results_loadingSummary: "正在加载摘要...",
  results_error_loading: "我们无法加载您的结果。如果您已付款，请",
  results_download_for_details: "要获取您的问卷、图像分析和当地专家列表的详细分解，请下载完整的 PDF 报告。",

  results_condition_cataract: "白内障发展",
  results_details_cataract: "观察到轻微的晶状体混浊，建议监测。",
  results_condition_glaucomaIndicators: "青光眼指标",
  results_details_glaucomaIndicators: "可能与青光眼相关的视觉迹象，例如视神经或虹膜的变化。",
  results_condition_ptosis: "上睑下垂",
  results_details_ptosis: "上眼睑低于正常位置，可能会影响视力。",
  results_condition_subconjunctivalHemorrhage: "结膜下出血",
  results_details_subconjunctivalHemorrhage: "眼球表面的血管破裂，通常无害但应进行检查。",
  results_condition_conjunctivitis: "感染/结膜炎",
  results_details_conjunctivitis: "结膜炎症或感染的迹象（红眼病），例如发红和分泌物。",
  results_condition_abnormalPupils: "瞳孔异常",
  results_details_abnormalPupils: "瞳孔大小不等、形状不规则或颜色异常，需要医疗评估。",
  results_condition_ocularJaundice: "眼黄疸",
  results_details_ocularJaundice: "眼睛白色部分变黄，可能表明肝脏问题。",
  results_condition_cornealArcus: "角膜弓",
  results_details_cornealArcus: "角膜周围出现白色、灰色或蓝色的环，有时与高胆固醇有关。",
  results_condition_inflammation: "炎症/发红",
  results_details_inflammation: "检测到一般炎症迹象、明显发红或分泌物。",
  results_condition_drynessOrTearing: "干燥/异常流泪",
  results_details_drynessOrTearing: "可能表明泪液产生问题的视觉迹象，例如过度干燥或流泪。",
  
  results_risk_low: "低",
  results_risk_medium: "中",
  results_risk_high: "高",
  results_risk_undetermined: "不确定",

  payment_title: "安全支付",
  payment_unlock_title: "解锁您的完整报告",
  payment_unlock_description: "一次性付款，即可获得详细分析的可下载 PDF 文件并保存记录。",
  payment_pay_now_button: "立即支付 10.00 美元",
  payment_processing: "处理中...",
  payment_support_prompt: "支付遇到问题？",
  payment_support_link: "联系支持",

  header_welcomeMessage: "欢迎, {email}",
  header_logoutButton: "登出",
  header_loginRegisterButton: "登录/注册",
  header_myProfileLink: "我的个人资料",
  header_adminPanel: "管理面板",
  header_doctorPortal: "医生门户",
  header_hrAdminPanel: "人力资源面板",
  header_pricingLink: "价格",
  header_ourTechnologyLink: "我们的技术",
  header_mobileAppLink: "移动应用",

  profile_title: "我的个人资料",
  profile_personal_info_title: "个人信息",
  profile_medical_info_title: "医疗信息",
  profile_reminders_title: "我的提醒",
  profile_history_title: "评估历史",
  profile_tab_personal_info: "个人信息",
  profile_tab_consultation: "咨询与提醒",
  history_evaluationDate: "评估日期",
  profile_noHistory: "您没有过去的评估。",
  profile_loading: "正在加载您的个人资料...",
  profile_fetchError: "无法加载您的个人资料。请稍后重试。",
  profile_doctor_note_title: "医生备注",
  profile_edit_button: "编辑个人资料",
  profile_save_button: "保存更改",
  profile_saving_button: "正在保存...",
  profile_cancel_button: "取消",
  profile_change_photo_button: "更改照片",
  profile_change_photo_prompt: "点击下方上传新的个人资料图片。",
  profile_uploading_photo: "正在上传...",
  profile_error_upload: "上传照片时出错。",
  profile_error_save: "保存个人资料时出错。",
  profile_label_phone: "电话号码",
  profile_placeholder_phone: "(555) 123-4567",
  profile_label_allergies: "过敏史",
  profile_placeholder_allergies: "例如，花粉、青霉素",
  profile_label_conditions: "医疗状况",
  profile_placeholder_conditions: "例如，2 型糖尿病",
  profile_label_surgeries: "既往手术史",
  profile_placeholder_surgeries: "例如，阑尾切除术（2015 年）",
  profile_reminders_none: "您没有活动的提醒。",
  profile_reminders_add_new: "添加新提醒",
  
  reminder_modal_title_add: "添加新提醒",
  reminder_modal_title_edit: "编辑提醒",
  reminder_type: "提醒类型",
  reminder_type_medication: "药物",
  reminder_type_consultation: "咨询",
  reminder_name_label: "名称/标题",
  reminder_name_placeholder_medication: "例如，拉坦前列素滴眼液",
  reminder_name_placeholder_consultation: "例如，与史密斯医生的随访",
  reminder_details_label: "详情/剂量",
  reminder_details_placeholder_medication: "例如，每只眼睛滴 1 滴",
  reminder_details_placeholder_consultation: "例如，检查青光眼进展",
  reminder_frequency_label: "频率",
  reminder_frequency_helper: "每...",
  reminder_frequency_hours: "小时",
  reminder_frequency_days: "天",
  reminder_frequency_weeks: "周",
  reminder_frequency_months: "月",
  reminder_starts_at_label: "首次提醒时间",
  reminder_save_button: "保存提醒",
  reminder_delete_button: "删除",
  reminder_next_due: "下次到期：",
  reminder_notification_permission_title: "启用通知",
  reminder_notification_permission_body: "要接收提醒，请允许 Niria 向您发送通知。",
  reminder_notification_denied: "通知被阻止。请在浏览器设置中启用它们以接收提醒。",
  reminder_notification_medication_title: "药物提醒",
  reminder_notification_consultation_title: "咨询提醒",
  
  admin_title: "管理仪表板",
  admin_manageUsers: "管理用户",
  admin_error_load_users: "无法加载用户列表。您可能没有权限。",
  admin_success_role_update: "用户角色已成功更新。",
  admin_error_role_update: "更改角色时发生错误。",
  admin_error_self_remove: "您不能删除自己的管理员状态。",
  admin_table_header_user: "用户",
  admin_table_header_role: "角色",
  admin_table_header_action: "操作",
  admin_role_admin: "管理员",
  admin_role_user: "用户",
  admin_role_premium: "高级会员",
  admin_role_doctor: "医生",
  admin_role_hr_admin: "人力资源管理员",
  admin_no_name: "无姓名",
  admin_action_remove: "移除管理员",
  admin_action_make: "设为管理员",
  admin_action_approve: "批准",
  admin_action_make_premium: "设为高级会员",
  admin_action_remove_premium: "移除高级会员",
  admin_action_make_doctor: "设为医生",
  admin_action_remove_doctor: "移除医生",
  admin_action_make_hr_admin: "设为人力资源管理员",
  admin_action_remove_hr_admin: "移除人力资源管理员",
  admin_success_premium_update: "高级会员状态已成功更新。",
  admin_error_premium_update: "更改高级会员状态时发生错误。",
  admin_tab_users: "用户管理",
  admin_tab_feedback: "反馈",
  admin_tab_stats: "仪表板",
  admin_tab_doctor_requests: "医生请求",
  admin_doctor_requests_title: "待批准的医生请求",
  admin_no_doctor_requests: "没有待批准的医生请求。",
  admin_feedback_title: "用户反馈",
  admin_feedback_table_header_rating: "评分",
  admin_feedback_table_header_comment: "评论",
  admin_feedback_table_header_date: "日期",
  admin_search_placeholder: "按姓名或电子邮件搜索...",
  admin_no_users_found: "未找到用户。",
  admin_no_users_match: "没有用户符合您的搜索条件。",
  admin_feedback_filter_by_rating: "按评分筛选",
  admin_feedback_filter_all: "全部",
  admin_feedback_filter_n_stars: "{count} 星",
  admin_no_feedback_found: "尚未提交任何反馈。",
  admin_no_feedback_match: "没有反馈符合所选筛选条件。",
  admin_stats_total_users: "总用户数",
  admin_stats_admins: "管理员",
  admin_stats_premium_users: "高级会员",
  admin_stats_doctors: "医生",
  admin_stats_hr_admins: "人力资源管理员",
  admin_stats_normal_users: "普通用户",
  admin_stats_total_evaluations: "总评估数",
  admin_stats_loading: "正在加载统计数据...",
  admin_stats_error: "无法加载统计数据。",

  hr_admin_title: "人力资源管理面板",
  hr_admin_tab_dashboard: "仪表板",
  hr_admin_tab_employees: "员工",
  hr_admin_tab_teams: "团队",
  hr_admin_dashboard_placeholder: "包含团队统计数据、警报和评估跟踪的仪表板即将推出。",
  hr_admin_employees_title: "管理员工",
  hr_admin_add_employee: "添加员工",
  hr_admin_no_employees: "尚未添加任何员工。",
  hr_admin_teams_title: "管理团队",
  hr_admin_add_team: "添加团队",
  hr_admin_no_teams: "尚未创建任何团队。",
  hr_admin_team_unassigned: "未分配",
  hr_modal_employee_title_add: "添加新员工",
  hr_modal_employee_title_edit: "编辑员工",
  hr_modal_team_title_add: "添加新团队",
  hr_modal_team_title_edit: "编辑团队",
  hr_field_firstName: "名字",
  hr_field_lastName: "姓氏",
  hr_field_email: "电子邮件",
  hr_field_team: "团队",
  hr_field_no_team: "无团队",
  hr_field_team_name: "团队名称",
  hr_button_save: "保存",
  hr_button_saving: "正在保存...",
  hr_button_cancel: "取消",
  hr_button_edit: "编辑",
  hr_table_header_name: "姓名",
  hr_table_header_email: "电子邮件",
  hr_table_header_team: "团队",
  hr_table_header_last_check: "上次检查",
  hr_table_header_actions: "操作",
  hr_dashboard_total_members: "团队总成员数",
  hr_dashboard_evaluations_pending: "待首次评估",
  hr_dashboard_evaluations_due_soon: "即将到期",
  hr_dashboard_evaluations_overdue: "已逾期",
  hr_dashboard_team_members_title: "团队成员状态",
  hr_dashboard_table_header_member: "成员",
  hr_dashboard_table_header_last_eval: "上次评估",
  hr_dashboard_table_header_next_eval: "下次评估",
  hr_dashboard_table_header_status: "状态",
  hr_dashboard_status_ok: "正常",
  hr_dashboard_status_due_soon: "即将到期",
  hr_dashboard_status_overdue: "已逾期",
  hr_dashboard_status_pending: "待定",
  hr_dashboard_no_eval_history: "无历史记录",
  hr_dashboard_loading_data: "正在加载仪表板数据...",

  pagination_previous: "上一页",
  pagination_next: "下一页",
  pagination_page_info: "第 {currentPage} 页，共 {totalPages} 页",
  
  doctor_portal_title: "医生门户",
  doctor_portal_loading: "正在加载患者评估...",
  doctor_portal_error: "无法加载评估。请稍后重试。",
  doctor_portal_no_evals: "未找到患者评估。",
  doctor_portal_table_patient: "患者",
  doctor_portal_table_date: "日期",
  doctor_portal_table_status: "状态",
  doctor_portal_table_action: "操作",
  doctor_portal_review_button: "审查",
  doctor_portal_view_button: "查看",
  doctor_portal_back_button: "返回门户",
  doctor_portal_status_pending: "待审查",
  doctor_portal_status_responded: "已响应",
  doctor_portal_search_placeholder: "按患者姓名搜索...",
  doctor_portal_no_match: "没有评估符合您的搜索条件。",

  evaluation_detail_title: "审查评估",
  evaluation_detail_add_note: "添加医生备注",
  evaluation_detail_note_placeholder: "在此输入您的专业诊断或评论...",
  evaluation_detail_add_button: "添加备注",
  evaluation_detail_adding_note: "正在添加备注...",
  evaluation_detail_previous_notes: "以前的备注",
  evaluation_detail_no_notes: "此评估尚未添加任何备注。",
  evaluation_detail_error: "无法添加备注。请重试。",
  evaluation_detail_your_note_title: "您提交的备注",
  evaluation_detail_note_submitted_on: "提交于",
  
  language_switcher_en: "英",
  language_switcher_es: "西",
  language_switcher_zh: "中文",

  support_title: "支持与帮助",
  support_heading: "需要帮助吗？",
  support_intro: "很抱歉您遇到了问题。我们的团队随时为您提供帮助。",
  support_instruction_email: "为尽快解决您的问题，请发送电子邮件至：",
  support_instruction_include: "请务必包含以下信息：",
  support_info_1: "您用于注册的电子邮件地址。",
  support_info_2: "交易的大致日期和时间。",
  support_info_3: "您遇到的问题的简要描述。",
  support_backToHomeButton: "返回主页",
  
  footer_supportLink: "支持",

  report_confidential_title: "机密眼部健康报告",
  report_date_generated: "生成日期",
  report_patient_info: "患者信息",
  report_patient_name: "姓名",
  report_patient_dob: "出生日期",
  report_patient_email: "电子邮件",
  report_ai_summary_title: "人工智能摘要",
  report_questionnaire_summary: "问卷摘要",
  report_image_analysis_details: "图像分析详情",
  report_submitted_image: "提交的图像",
  report_no_findings: "初步图像分析未根据提供的图像检测到任何重大疾病的直接迹象。",
  report_nearby_ophthalmologists: "附近的眼科医生",
  report_phone: "电话",
  report_doctor_notes_title: "医生备注",
  questionnaire_reason: "评估原因",
  questionnaire_lenses: "佩戴眼镜",
  questionnaire_satisfactionLabel: "满意度",
  questionnaire_lastUpdateLabel: "上次更新",
  questionnaire_surgery: "曾有手术/损伤",
  questionnaire_surgeryOrInjuryDetails: "详情",
  questionnaire_illnesses: "全身性疾病",
  questionnaire_familyHistory: "家族眼病史",
  questionnaire_symptoms: "当前症状",
  questionnaire_not_answered: "未回答",
  date_locale: "zh-CN",

  pricing_title: "选择您的计划",
  pricing_subtitle: "简单透明的定价，满足各种需求。",
  pricing_plan_individual_title: "个人分析",
  pricing_plan_individual_price: "3.99美元",
  pricing_plan_individual_frequency: "一次性支付",
  pricing_plan_individual_feature1: "人工智能分析",
  pricing_plan_individual_feature2: "可下载的 PDF 报告",
  pricing_plan_individual_feature3: "附近专家列表",
  pricing_cta_get_started: "开始",
  pricing_plan_plus_title: "健康套餐",
  pricing_plan_plus_price: "4.99美元",
  pricing_plan_plus_frequency: "一次性支付",
  pricing_plan_plus_feature1: "包含个人版所有功能",
  pricing_plan_plus_feature2: "包括 2 次评估",
  pricing_cta_choose_plus: "选择套餐",
  pricing_plan_business_title: "Niria 商业版",
  pricing_plan_business_price: "定制",
  pricing_plan_business_frequency: "按年计费",
  pricing_plan_business_feature1: "员工批量评估",
  pricing_plan_business_feature2: "人力资源管理仪表板",
  pricing_plan_business_feature3: "员工健康跟踪",
  pricing_plan_business_feature4: "优先支持",
  pricing_cta_contact_sales: "联系销售",
  pricing_best_value: "最具价值",

  our_tech_title: "我们的技术",
  our_tech_subtitle: "探索为 Niria 智能眼部健康分析提供动力的创新技术。",
  our_tech_how_it_works_title: "工作原理：简单的四步流程",
  our_tech_step1_title: "1. 拍摄",
  our_tech_step1_desc: "用户通过我们的引导界面，使用智能手机摄像头拍摄一张清晰、光线充足的眼部照片。",
  our_tech_step2_title: "2. 分析",
  our_tech_step2_desc: "图像连同相关的健康数据被发送到我们的安全后端，并由我们的专有 AI 模型进行分析。",
  our_tech_step3_title: "3. 报告",
  our_tech_step3_desc: "几分钟内，系统会生成一份易于理解的初步报告，突出潜在的关注领域，并提供个性化的健康提示。",
  our_tech_step4_title: "4. 连接",
  our_tech_step4_desc: "根据分析和用户的位置，我们提供一份附近的眼科医生列表，以促进迈向专业护理的下一步。",
  our_tech_key_technologies_title: "关键技术",
  our_tech_tech1_title: "人工智能与机器学习",
  our_tech_tech1_desc: "我们的核心是一个复杂的专有 AI 模型，经过训练可以识别与各种眼部健康指标相关的视觉模式。它不断学习以提高其准确性和洞察力。",
  our_tech_tech2_title: "安全的云基础设施",
  our_tech_tech2_desc: "我们的平台建立在可扩展且安全的云基础设施之上，确保为每个用户提供高可用性、快速处理和数据完整性，无论他们身在何处。",
  our_tech_tech3_title: "数据隐私与合规",
  our_tech_tech3_desc: "我们通过端到端加密优先考虑用户隐私，并遵守严格的数据保护标准。您的健康信息经过匿名化处理，并以最高的机密性处理。",
  our_tech_integration_title: "集成可能性",
  our_tech_integration_subtitle: "Niria 旨在成为一个灵活而强大的工具。我们提供合作机会，将我们的技术集成到您的平台中。",
  our_tech_integration1_title: "远程医疗平台",
  our_tech_integration1_desc: "使用我们的初步筛查工具增强您的虚拟咨询，以更好地优先处理和指导患者。",
  our_tech_integration2_title: "企业健康计划",
  our_tech_integration2_desc: "为您的员工提供积极的健康福利，帮助及早发现潜在问题并促进福祉。",
  our_tech_integration3_title: "医疗保健提供者",
  our_tech_integration3_desc: "将我们的技术整合到您的患者入院流程中，以收集初步数据并简化诊所工作流程。",
  our_tech_contact_us_button: "联系我们进行演示",
  
  mobile_title: "Niria 即将登陆移动端",
  mobile_subtitle: "随时随地体验无缝的眼部健康监测。我们的移动应用即将推出！",
  mobile_countdown_title: "上线倒计时",
  mobile_days: "天",
  mobile_hours: "小时",
  mobile_minutes: "分钟",
  mobile_seconds: "秒",
  mobile_coming_soon: "即将推出",
  mobile_download_on: "在...下载",
  mobile_get_it_on: "获取于",

  home_promo_mobile_title: "移动版 Niria",
  home_promo_mobile_subtitle: "我们全套的眼部健康工具即将登陆专属移动应用。准备好迎接无缝体验吧。",
  home_promo_mobile_cta: "了解更多并查看倒计时",

  error_generic_api_key_missing: "AI 服务不可用：缺少 API 密钥。请联系支持。",
  error_generic_api_key_invalid: "AI 服务不可用：配置的 API 密钥无效。请联系支持。",
  error_generic_api_fetch_failed: "由于 API 错误，获取提示失败：{errorMessage}",
  error_generic_unexpected_api: "与 AI 服务通信时发生意外错误。请重试。",
  error_generic_api_timeout: "AI 服务响应时间过长。请重试。",
  error_image_processing: "无法处理图像。请重试。",
  error_generic_no_tips_received: "未从 AI 收到任何提示。请稍后重试。",
  error_analysis_blocked: "由于提交的图像不清晰或不当，无法完成分析。请使用清晰的眼部照片重试。",
  
  report_download_pdf_button: "下载 PDF 报告",
  report_downloading_pdf: "正在下载...",
  feedback_button: "提供反馈",
  feedback_submitted: "已提交反馈",
  feedback_thanks_title: "谢谢！",
  feedback_thanks_message: "您的反馈已成功提交。",
  feedback_title: "评价您的体验",
  feedback_subtitle: "您的意见帮助我们改进。",
  feedback_comment_placeholder: "留下可选评论...",
  feedback_close_button: "关闭",
  feedback_submit_button: "提交反馈",
};
