
export const en = {
  appName: "Virtual Vision Test",
  appMotto: "The future of eye care starts with a photo.",
  appSubMotto: "Get rapid, AI-powered insights into your eye health from the comfort of your home.",
  footerText: "© TREASURES OF ZIMA LLC.",
  footerDisclaimer: "Virtual Vision Test is an informational tool and does not provide medical advice.",
  missionStatement: "Our mission is to democratize eye health by providing accessible, affordable, and reliable AI-driven analysis to everyone, everywhere. We believe early detection is key to preserving vision.",
  resultsDisclaimerShort: "Not medical advice. Consult a doctor.",
  resultsDisclaimer: "Important: The analysis provided by Virtual Vision Test is for informational purposes only and is not a substitute for a professional medical diagnosis. Always consult with a qualified ophthalmologist or healthcare provider for any eye health concerns or before making any decisions related to your health or treatment.",
  paymentPlaceholderText: "Our secure payment portal is coming soon. In a real application, this page would integrate with a payment processor like Stripe or PayPal to handle transactions securely.",

  home_ctaButton: "Start Analysis",
  home_whyChooseOculusIA: "Why Choose Virtual Vision Test?",
  home_ourMission: "Our Mission",

  feature_resultsInMinutes_title: "Results in Minutes",
  feature_resultsInMinutes_description: "Our advanced AI provides a preliminary analysis of your eye photo quickly and efficiently.",
  feature_noExpensiveEquipment_title: "No Expensive Equipment",
  feature_noExpensiveEquipment_description: "All you need is a smartphone or a digital camera to take a photo of your eye.",
  feature_highAccuracyPotential_title: "High Accuracy Potential",
  feature_highAccuracyPotential_description: "Leveraging cutting-edge AI models for pattern recognition in eye health indicators.",
  feature_securePrivate_title: "Secure & Private",
  feature_securePrivate_description: "Your data is handled with the utmost care, ensuring privacy and security.",

  auth_loginToAccount: "Sign In to Your Account",
  auth_createAccount: "Create an Account",
  auth_firstNameLabel: "First Name",
  auth_firstNamePlaceholder: "Jane",
  auth_lastNameLabel: "Last Name",
  auth_lastNamePlaceholder: "Doe",
  auth_emailLabel: "Email Address",
  auth_emailPlaceholder: "you@example.com",
  auth_passwordLabel: "Password",
  auth_signInButton: "Sign In",
  auth_signUpButton: "Create Account",
  auth_googleSignInButton: "Sign in with Google",
  auth_loggingInButton: "Signing in...",
  auth_registeringButton: "Creating account...",
  auth_dontHaveAccount: "Don't have an account?",
  auth_signUpHereLink: "Sign Up",
  auth_alreadyHaveAccount: "Already have an account?",
  auth_signInHereLink: "Sign In",
  auth_orDivider: "OR",
  auth_forgot_password_link: "Forgot Password?",
  auth_reset_password_title: "Reset Password",
  auth_reset_password_instructions: "Enter the email address associated with your account, and we'll send you a link to reset your password.",
  auth_send_link_button: "Send Reset Link",
  auth_sending_link_button: "Sending Link...",
  auth_back_to_signin_link: "← Back to Sign In",
  auth_reset_link_sent: "Password reset link sent successfully. Please check your email inbox and spam folder.",
  auth_error_passwordsDoNotMatch: "Passwords do not match.",
  auth_error_loginFailed: "Login failed. Please check your credentials.",
  auth_error_registrationFailed: "Registration failed. Please try again.",
  auth_error_unexpected: "An unexpected error occurred. Please try again.",
  auth_error_email_in_use: "This email address is already in use by another account.",
  auth_error_weak_password: "Password is too weak. It should be at least 6 characters.",
  auth_error_user_not_found: "No account found with this email address.",
  auth_error_wrong_password: "Incorrect password. Please try again.",
  auth_error_invalid_email: "The email address is not valid.",

  exam_title: "Eye Health Analysis",
  exam_instructions: "For best results, ensure your eye is well-lit and in focus. Remove glasses or contact lenses if possible. The image should clearly show your iris and pupil.",
  exam_uploadPhotoButton: "Upload Photo",
  exam_stopCameraButton: "Stop Camera",
  exam_takePhotoWithCameraButton: "Take Photo with Camera",
  exam_capturePhotoButton: "Capture Photo",
  exam_imagePreviewTitle: "Image Preview:",
  exam_livePreviewTitle: "Live Camera Preview",
  exam_analyzeButton: "Analyze Eye Photo",
  exam_analyzingText: "Analyzing your photo...",
  exam_error_fileTooLarge: "File is too large. Maximum size is 5MB.",
  exam_error_invalidFileType: "Invalid file type. Please upload a JPG, PNG, or WEBP image.",
  exam_error_noPhoto: "Please upload or take a photo of your eye first.",
  exam_error_cameraAccess: "Could not access camera. Please ensure permissions are granted.",
  exam_error_cameraNotSupported: "Camera not supported on this browser.",
  exam_error_analysisFailed: "An error occurred during the analysis. Please check your connection and try again.",
  exam_error_missingData: "User data or health questionnaire is missing. Please restart the process from the home page.",
  exam_error_invalid_image_data: "The provided image data is invalid. Please try capturing or uploading the photo again.",
  exam_guidedCaptureButton: "Start Guided Capture",
  exam_retryButton: "Retry",
  exam_retakePhotoButton: "Retake Photo",
  exam_cancelButton: "Cancel",
  
  exam_guide_welcome: "We're going to get the best image of your eyes. Find a well-lit place and clean your camera lens. If you have a disability, please ask for assistance.",
  exam_guide_start_process: "Let's begin. Please, look at the camera.",
  exam_guide_no_person: "No face detected. Please position yourself in the center.",
  exam_guide_too_many: "Only one person at a time, please.",
  exam_guide_center_face: "Please, center your face.",
  exam_guide_get_closer: "A little closer, please.",
  exam_guide_open_eyes: "Excellent! Now, please open your eyes wide.",
  exam_guide_perfect: "Perfect, hold that pose!",
  exam_guide_capture_success: "Image captured successfully!",
  exam_guide_timeout: "We couldn't get a clear image. This may be due to low light or camera quality. Please find a better-lit spot and press Retry.",
  exam_guide_retry: "Let's try again.",
  exam_guide_initializing: "Initializing camera...",

  questionnaire_title: "Patient Health Questionnaire",
  questionnaire_intro: "Please answer the following questions to provide context for your analysis.",
  questionnaire_submitButton: "Continue to Photo Capture",
  
  q_option_other_not_sure: "Other / Not sure",

  q_firstNameLabel: "First Name",
  q_firstNamePlaceholder: "Jane",
  q_lastNameLabel: "Last Name",
  q_lastNamePlaceholder: "Doe",
  q_dob_label: "Date of Birth",
  q_dob_day_placeholder: "Day",
  q_dob_month_placeholder: "Month",
  q_dob_year_placeholder: "Year",
  month_january: "January",
  month_february: "February",
  month_march: "March",
  month_april: "April",
  month_may: "May",
  month_june: "June",
  month_july: "July",
  month_august: "August",
  month_september: "September",
  month_october: "October",
  month_november: "November",
  month_december: "December",

  q1_label_new: "1. What is the reason for taking this evaluation?",
  q1_option_blurry: "Blurry or altered vision",
  q1_option_tired: "Tired or fatigued eyes",
  q1_option_redness: "Redness or irritation",
  q1_option_checkup: "Periodic check-up",

  q2_label: "2. Do you wear lenses (glasses or contact lenses)?",
  q2_yes: "Yes",
  q2_no: "No",
  q2_satisfactionLabel: "If so, how satisfied are you with them?",
  q2_satisfactionPlaceholder: "e.g., They work well, I get headaches...",
  q2_lastUpdateLabel: "When was the last time you had your prescription updated?",
  q2_lastUpdatePlaceholder: "e.g., 6 months ago, over 2 years ago...",
  q3_label: "3. Have you ever had eye surgery, a major injury or trauma, or a serious eye infection?",
  q3_detailsLabel: "If yes, please provide details.",
  q3_detailsPlaceholder: "e.g., LASIK in 2018, corneal scratch...",
  q4_label: "4. Do you have any major general illnesses?",
  q4_illness_diabetes: "Diabetes",
  q4_illness_highBloodPressure: "High Blood Pressure",
  q4_illness_highCholesterol: "High Cholesterol",
  q4_illness_thyroid: "Thyroid Disease",
  q4_illness_arthritis: "Arthritis",
  q5_label: "5. Does anyone in your immediate family have any significant eye conditions?",
  q5_condition_glaucoma: "Glaucoma",
  q5_condition_macularDegeneration: "Macular Degeneration",
  q5_condition_strabismus: "Strabismus",
  q5_condition_highMyopia: "High Myopia",
  q6_label: "6. In addition to your main complaint, have you experienced any of the following symptoms?",
  q6_symptom_pain: "Pain",
  q6_symptom_itching: "Itching",
  q6_symptom_burning: "Burning",
  q6_symptom_tearing: "Excessive tearing",
  q6_symptom_gritty: "Gritty sensation",
  q6_symptom_lightSensitivity: "Sensitivity to light",
  q6_symptom_doubleVision: "Double vision",
  q6_symptom_none: "None of the above",
  
  error_validation_name: "Please enter your first and last name.",
  error_validation_dob_full: "Please select your complete date of birth (day, month, and year).",

  results_title: "Your Eye Health Analysis",
  results_summaryTitle: "AI-Powered Summary",
  results_detailedFindingsTitle: "Detailed Findings from Image Analysis",
  results_noResults: "No analysis results to display.",
  results_riskLevelSuffix: "Risk",
  results_importantDisclaimerTitle: "Important Disclaimer",
  results_generalEyeHealthTipsTitle: "General Eye Health Tips",
  results_fetchingTips: "Fetching tips...",
  results_error_couldNotLoadTips: "Could not load eye health tips at this time. Please try again later.",
  results_refreshTipsButton: "Refresh Tips",
  results_proceedToPaymentButton: "Proceed to Payment",
  results_performAnotherAnalysisButton: "Perform Another Analysis",
  results_backToHomeButton: "Back to Home",
  results_loadingSummary: "Loading summary...",
  results_error_loading: "We were unable to load your results. If you have already paid, please",

  results_condition_cornealAbrasion: "Corneal Abrasion",
  results_details_cornealAbrasion: "Minor surface irregularities detected, likely superficial.",
  results_condition_cataract: "Cataract Development",
  results_details_cataract: "Slight lens opacity observed, recommend monitoring.",
  results_condition_glaucoma: "Glaucoma Indicators",
  results_details_glaucoma: "Optic nerve features require further professional assessment.",
  
  results_risk_low: "Low",
  results_risk_medium: "Medium",
  results_risk_high: "High",
  results_risk_undetermined: "Undetermined",

  payment_title: "Secure Payment",
  payment_unlock_title: "Unlock Your Full Report",
  payment_unlock_description: "For a one-time fee, get a downloadable PDF of your detailed analysis and keep it for your records.",
  payment_pay_now_button: "Pay $10.00 Now",
  payment_processing: "Processing...",
  payment_support_prompt: "Problems with your payment?",
  payment_support_link: "Contact Support",

  header_welcomeMessage: "Welcome, {email}",
  header_logoutButton: "Logout",
  header_loginRegisterButton: "Sign In / Sign Up",
  header_myResultsLink: "My Results",
  header_adminPanel: "Admin Panel",

  history_title: "My Results",
  history_summaryTitle: "Summary",
  history_totalEvaluations: "Total Evaluations",
  history_lastEvaluation: "Last Evaluation",
  history_historyTitle: "Evaluation History",
  history_evaluationDate: "Evaluation Date",
  history_viewReportButton: "View / Re-print Report",
  history_generatingReport: "Generating Report...",
  history_noHistory: "You have no past evaluations.",
  history_loading: "Loading your history...",
  history_fetchError: "Could not load your evaluation history. Please try again later.",

  admin_title: "Admin Dashboard",
  admin_manageUsers: "Manage Users",
  admin_error_load_users: "Could not load user list. You may not have permission.",
  admin_success_role_update: "User role updated successfully.",
  admin_error_role_update: "An error occurred while changing the role.",
  admin_error_self_remove: "You cannot remove your own admin status.",
  admin_table_header_user: "User",
  admin_table_header_role: "Role",
  admin_table_header_action: "Action",
  admin_role_admin: "Admin",
  admin_role_user: "User",
  admin_no_name: "No Name",
  admin_action_remove: "Remove Admin",
  admin_action_make: "Make Admin",
  admin_tab_users: "User Management",
  admin_tab_feedback: "Feedback",
  admin_feedback_title: "User Feedback",
  admin_feedback_table_header_rating: "Rating",
  admin_feedback_table_header_comment: "Comment",
  admin_feedback_table_header_date: "Date",


  language_switcher_en: "EN",
  language_switcher_es: "ES",

  support_title: "Support & Help",
  support_heading: "Need Assistance?",
  support_intro: "We're sorry you're experiencing an issue. Our team is here to help.",
  support_instruction_email: "To resolve your issue as quickly as possible, please send us an email at:",
  support_instruction_include: "Please be sure to include the following information:",
  support_info_1: "The email address you used to sign up.",
  support_info_2: "The approximate date and time of the transaction.",
  support_info_3: "A brief description of the problem you experienced.",
  support_backToHomeButton: "Back to Home Page",
  
  footer_supportLink: "Support",
  
  report_confidential_title: "Confidential Eye Health Report",
  report_date_generated: "Date Generated",
  report_patient_info: "Patient Information",
  report_patient_name: "Name",
  report_patient_dob: "Date of Birth",
  report_patient_email: "Email",
  report_ai_summary_title: "AI-Powered Summary",
  report_questionnaire_summary: "Questionnaire Summary",
  report_image_analysis_details: "Image Analysis Details",
  report_submitted_image: "Submitted Image",
  report_no_findings: "The initial image analysis did not detect any immediate signs of major conditions based on the provided image.",
  questionnaire_reason: "Reason for evaluation",
  questionnaire_lenses: "Wears lenses",
  questionnaire_satisfactionLabel: "Satisfaction",
  questionnaire_lastUpdateLabel: "Last update",
  questionnaire_surgery: "Had surgery/injury",
  questionnaire_surgeryOrInjuryDetails: "Details",
  questionnaire_illnesses: "General illnesses",
  questionnaire_familyHistory: "Family eye history",
  questionnaire_symptoms: "Current symptoms",
  questionnaire_not_answered: "Not answered",
  date_locale: "en-US",

  // Generic
  error_generic_api_key_missing: "AI service is unavailable: API Key is missing. Please contact support.",
  error_generic_api_key_invalid: "AI service is unavailable: The configured API key is invalid. Please contact support.",
  error_generic_api_fetch_failed: "Failed to fetch tips due to an API error: {errorMessage}",
  error_generic_unexpected_api: "An unexpected error occurred while communicating with the AI service. Please try again.",
  error_generic_no_tips_received: "No tips received from the AI. Please try again later.",
  error_analysis_blocked: "Analysis could not be completed because the submitted image was unclear or inappropriate. Please try again with a clear photo of just your eye.",

  report_download_pdf_button: "Download PDF Report",
  report_downloading_pdf: "Downloading...",
  feedback_button: "Give Feedback",
  feedback_submitted: "Feedback Submitted",
  feedback_thanks_title: "Thank You!",
  feedback_thanks_message: "Your feedback has been submitted successfully.",
  feedback_title: "Rate Your Experience",
  feedback_subtitle: "Your opinion helps us improve.",
  feedback_comment_placeholder: "Leave an optional comment...",
  feedback_close_button: "Close",
  feedback_submit_button: "Submit Feedback",
};

export type TranslationKeys = typeof en;
