

import { TranslationKeys } from './en';

export const es: TranslationKeys = {
  appName: "Virtual Vision Test",
  appMotto: "El futuro del cuidado ocular comienza con una foto.",
  appSubMotto: "Obtenga información rápida sobre la salud de sus ojos, impulsada por IA, desde la comodidad de su hogar.",
  footerText: "© TREASURES OF ZIMA LLC.",
  footerDisclaimer: "Virtual Vision Test es una herramienta informativa y no proporciona asesoramiento médico.",
  missionStatement: "Nuestra misión es democratizar la salud ocular proporcionando un análisis accesible, asequible y fiable impulsado por IA para todos, en todas partes. Creemos que la detección temprana es clave para preservar la visión.",
  resultsDisclaimerShort: "No es consejo médico. Consulte a un doctor.",
  resultsDisclaimer: "Importante: El análisis proporcionado por Virtual Vision Test es solo para fines informativos y no sustituye un diagnóstico médico profesional. Consulte siempre a un oftalmólogo calificado o proveedor de atención médica para cualquier inquietud sobre la salud ocular o antes de tomar decisiones relacionadas con su salud o tratamiento.",
  paymentPlaceholderText: "Nuestro portal de pago seguro estará disponible próximamente. En una aplicación real, esta página se integraría con un procesador de pagos como Stripe o PayPal para manejar las transacciones de forma segura.",

  home_ctaButton: "Iniciar Análisis",
  home_whyChooseOculusIA: "¿Por Qué Elegir Virtual Vision Test?",
  home_ourMission: "Nuestra Misión",

  feature_resultsInMinutes_title: "Resultados en Minutos",
  feature_resultsInMinutes_description: "Nuestra IA avanzada proporciona un análisis preliminar de la foto de su ojo de forma rápida y eficiente.",
  feature_noExpensiveEquipment_title: "Sin Equipos Costosos",
  feature_noExpensiveEquipment_description: "Todo lo que necesita es un smartphone o una cámara digital para tomar una foto de su ojo.",
  feature_highAccuracyPotential_title: "Potencial de Alta Precisión",
  feature_highAccuracyPotential_description: "Aprovechando modelos de IA de vanguardia para el reconocimiento de patrones en indicadores de salud ocular.",
  feature_securePrivate_title: "Seguro y Privado",
  feature_securePrivate_description: "Sus datos se manejan con el máximo cuidado, garantizando la privacidad y seguridad.",

  auth_loginToAccount: "Inicia Sesión en Tu Cuenta",
  auth_createAccount: "Crear una Cuenta",
  auth_firstNameLabel: "Nombre",
  auth_firstNamePlaceholder: "Juana",
  auth_lastNameLabel: "Apellido",
  auth_lastNamePlaceholder: "Pérez",
  auth_emailLabel: "Correo Electrónico",
  auth_emailPlaceholder: "usted@ejemplo.com",
  auth_passwordLabel: "Contraseña",
  auth_signInButton: "Iniciar Sesión",
  auth_signUpButton: "Crear Cuenta",
  auth_googleSignInButton: "Iniciar sesión con Google",
  auth_loggingInButton: "Iniciando sesión...",
  auth_registeringButton: "Creando cuenta...",
  auth_dontHaveAccount: "¿No tienes una cuenta?",
  auth_signUpHereLink: "Regístrate",
  auth_alreadyHaveAccount: "¿Ya tienes una cuenta?",
  auth_signInHereLink: "Inicia Sesión",
  auth_orDivider: "O",
  auth_forgot_password_link: "¿Olvidaste tu contraseña?",
  auth_reset_password_title: "Restablecer Contraseña",
  auth_reset_password_instructions: "Ingresa el correo electrónico asociado con tu cuenta y te enviaremos un enlace para restablecer tu contraseña.",
  auth_send_link_button: "Enviar Enlace de Restablecimiento",
  auth_sending_link_button: "Enviando Enlace...",
  auth_back_to_signin_link: "← Volver a Iniciar Sesión",
  auth_reset_link_sent: "¡Enlace de restablecimiento enviado! Por favor, revisa tu bandeja de entrada y la carpeta de spam.",
  auth_error_passwordsDoNotMatch: "Las contraseñas no coinciden.",
  auth_error_loginFailed: "Falló el inicio de sesión. Por favor verifique sus credenciales.",
  auth_error_registrationFailed: "Falló el registro. Por favor inténtelo de nuevo.",
  auth_error_unexpected: "Ocurrió un error inesperado. Por favor, inténtelo de nuevo.",
  auth_error_email_in_use: "Esta dirección de correo electrónico ya está en uso por otra cuenta.",
  auth_error_weak_password: "La contraseña es demasiado débil. Debe tener al menos 6 caracteres.",
  auth_error_user_not_found: "No se encontró ninguna cuenta con esta dirección de correo electrónico.",
  auth_error_wrong_password: "Contraseña incorrecta. Por favor, inténtelo de nuevo.",
  auth_error_invalid_email: "La dirección de correo electrónico no es válida.",

  exam_title: "Análisis de Salud Ocular",
  exam_instructions: "Para mejores resultados, asegúrese de que su ojo esté bien iluminado y enfocado. Quítese las gafas o lentes de contacto si es posible. La imagen debe mostrar claramente su iris y pupila.",
  exam_uploadPhotoButton: "Subir Foto",
  exam_stopCameraButton: "Detener Cámara",
  exam_takePhotoWithCameraButton: "Tomar Foto con Cámara",
  exam_capturePhotoButton: "Capturar Foto",
  exam_imagePreviewTitle: "Vista Previa de Imagen:",
  exam_livePreviewTitle: "Vista Previa de la Cámara en Vivo",
  exam_analyzeButton: "Analizar Foto del Ojo",
  exam_analyzingText: "Analizando su foto...",
  exam_error_fileTooLarge: "El archivo es demasiado grande. El tamaño máximo es 5MB.",
  exam_error_invalidFileType: "Tipo de archivo inválido. Por favor suba una imagen JPG, PNG, o WEBP.",
  exam_error_noPhoto: "Por favor suba o tome una foto de su ojo primero.",
  exam_error_cameraAccess: "No se pudo acceder a la cámara. Por favor asegúrese de que los permisos están concedidos.",
  exam_error_cameraNotSupported: "La cámara no es compatible con este navegador.",
  exam_error_analysisFailed: "Ocurrió un error durante el análisis. Por favor, compruebe su conexión e inténtelo de nuevo.",
  exam_error_missingData: "Faltan los datos del usuario o el cuestionario de salud. Por favor, reinicie el proceso desde la página de inicio.",
  exam_error_invalid_image_data: "Los datos de la imagen proporcionada no son válidos. Vuelva a intentar capturar o subir la foto.",
  exam_guidedCaptureButton: "Iniciar Captura Guiada",
  exam_retryButton: "Reintentar",
  exam_retakePhotoButton: "Volver a Tomar",
  exam_cancelButton: "Cancelar",

  exam_guide_welcome: "Vamos a tratar de conseguir la mejor imagen posible de tus ojos. Colócate en un lugar iluminado y limpia los lentes de la cámara lo mejor posible. Si tienes alguna discapacidad, solicita ayuda para que alguien tome una foto de tus ojos.",
  exam_guide_start_process: "Comencemos. Por favor, mira a la cámara.",
  exam_guide_no_person: "No se detecta un rostro. Por favor, colóquese en el centro de la imagen.",
  exam_guide_too_many: "Solo una persona a la vez, por favor.",
  exam_guide_center_face: "Por favor, céntrate un poco más.",
  exam_guide_get_closer: "Un poco más cerca, por favor.",
  exam_guide_open_eyes: "¡Excelente! Ahora, por favor, abre bien los ojos.",
  exam_guide_perfect: "¡Perfecto, mantén la pose!",
  exam_guide_capture_success: "¡Imagen capturada con éxito!",
  exam_guide_timeout: "No hemos podido obtener una imagen clara. Esto puede deberse a la baja iluminación o a la calidad de la cámara. Por favor, busca un lugar mejor iluminado y presiona Reintentar.",
  exam_guide_retry: "Vamos a intentarlo de nuevo.",
  exam_guide_initializing: "Iniciando cámara...",
  
  questionnaire_title: "Cuestionario de Salud del Paciente",
  questionnaire_intro: "Por favor, responda las siguientes preguntas para proporcionar contexto para su análisis.",
  questionnaire_submitButton: "Continuar a la Captura de Foto",

  q_option_other_not_sure: "Otro / No estoy seguro",
  
  q_firstNameLabel: "Nombre",
  q_firstNamePlaceholder: "Juana",
  q_lastNameLabel: "Apellido",
  q_lastNamePlaceholder: "Pérez",
  q_dob_label: "Fecha de Nacimiento",
  q_dob_day_placeholder: "Día",
  q_dob_month_placeholder: "Mes",
  q_dob_year_placeholder: "Año",
  month_january: "Enero",
  month_february: "Febrero",
  month_march: "Marzo",
  month_april: "Abril",
  month_may: "Mayo",
  month_june: "Junio",
  month_july: "Julio",
  month_august: "Agosto",
  month_september: "Septiembre",
  month_october: "Octubre",
  month_november: "Noviembre",
  month_december: "Diciembre",

  q1_label_new: "1. ¿Cuál es el motivo para realizar esta evaluación?",
  q1_option_blurry: "Visión borrosa o alterada",
  q1_option_tired: "Ojos cansados o fatigados",
  q1_option_redness: "Enrojecimiento o irritación",
  q1_option_checkup: "Chequeo periódico",

  q2_label: "2. ¿Usa lentes (gafas o lentes de contacto)?",
  q2_yes: "Sí",
  q2_no: "No",
  q2_satisfactionLabel: "Si es así, ¿qué tan satisfecho está con ellos?",
  q2_satisfactionPlaceholder: "Ej: Funcionan bien, me dan dolores de cabeza...",
  q2_lastUpdateLabel: "¿Cuándo fue la última vez que actualizó su prescripción?",
  q2_lastUpdatePlaceholder: "Ej: Hace 6 meses, hace más de 2 años...",
  q3_label: "3. ¿Ha tenido alguna vez una cirugía ocular, una lesión o trauma importante, o una infección ocular grave?",
  q3_detailsLabel: "Si es así, por favor proporcione detalles.",
  q3_detailsPlaceholder: "Ej: LASIK en 2018, rasguño corneal...",
  q4_label: "4. ¿Tiene alguna enfermedad general importante?",
  q4_illness_diabetes: "Diabetes",
  q4_illness_highBloodPressure: "Presión arterial alta",
  q4_illness_highCholesterol: "Colesterol alto",
  q4_illness_thyroid: "Enfermedad de la tiroides",
  q4_illness_arthritis: "Artritis",
  q5_label: "5. ¿Alguien en su familia inmediata (padres, abuelos, hermanos) tiene alguna condición ocular significativa?",
  q5_condition_glaucoma: "Glaucoma",
  q5_condition_macularDegeneration: "Degeneración macular",
  q5_condition_strabismus: "Estrabismo",
  q5_condition_highMyopia: "Miopía alta",
  q6_label: "6. Además de su queja principal, ¿ha experimentado alguno de los siguientes síntomas?",
  q6_symptom_pain: "Dolor",
  q6_symptom_itching: "Picazón",
  q6_symptom_burning: "Ardor",
  q6_symptom_tearing: "Lagrimeo excesivo",
  q6_symptom_gritty: "Sensación de arenilla",
  q6_symptom_lightSensitivity: "Sensibilidad a la luz",
  q6_symptom_doubleVision: "Visión doble",
  q6_symptom_none: "Ninguno de los anteriores",

  error_validation_name: "Por favor, ingrese su nombre y apellido.",
  error_validation_dob_full: "Por favor, seleccione su fecha de nacimiento completa (día, mes y año).",

  results_title: "Su Análisis de Salud Ocular",
  results_summaryTitle: "Resumen Impulsado por IA",
  results_detailedFindingsTitle: "Hallazgos Detallados del Análisis de Imagen",
  results_noResults: "No hay resultados de análisis para mostrar.",
  results_riskLevelSuffix: "Riesgo",
  results_importantDisclaimerTitle: "Descargo de Responsabilidad Importante",
  results_generalEyeHealthTipsTitle: "Consejos Generales de Salud Ocular",
  results_fetchingTips: "Obteniendo consejos...",
  results_error_couldNotLoadTips: "No se pudieron cargar los consejos de salud ocular en este momento. Por favor, inténtelo de nuevo más tarde.",
  results_refreshTipsButton: "Actualizar Consejos",
  results_proceedToPaymentButton: "Proceder al Pago",
  results_performAnotherAnalysisButton: "Realizar Otro Análisis",
  results_backToHomeButton: "Volver al Inicio",
  results_loadingSummary: "Cargando resumen...",
  results_error_loading: "No pudimos cargar sus resultados. Si ya ha pagado, por favor",

  results_condition_cornealAbrasion: "Abrasión Corneal",
  results_details_cornealAbrasion: "Se detectaron irregularidades menores en la superficie, probablemente superficiales.",
  results_condition_cataract: "Desarrollo de Cataratas",
  results_details_cataract: "Se observó una ligera opacidad del cristalino, se recomienda seguimiento.",
  results_condition_glaucoma: "Indicadores de Glaucoma",
  results_details_glaucoma: "Las características del nervio óptico requieren una evaluación profesional adicional.",

  results_risk_low: "Bajo",
  results_risk_medium: "Medio",
  results_risk_high: "Alto",
  results_risk_undetermined: "Indeterminado",
  
  payment_title: "Pago Seguro",
  payment_unlock_title: "Desbloquee su Informe Completo",
  payment_unlock_description: "Por un pago único, obtenga un PDF descargable de su análisis detallado y guárdelo para sus registros.",
  payment_pay_now_button: "Pagar $10.00 Ahora",
  payment_processing: "Procesando...",
  payment_support_prompt: "¿Problemas con tu pago?",
  payment_support_link: "Contacta a Soporte",

  header_welcomeMessage: "Bienvenido, {email}",
  header_logoutButton: "Cerrar Sesión",
  header_loginRegisterButton: "Iniciar Sesión / Registrarse",
  header_myResultsLink: "Mis Resultados",
  header_adminPanel: "Panel de Admin",

  history_title: "Mis Resultados",
  history_summaryTitle: "Resumen",
  history_totalEvaluations: "Evaluaciones Totales",
  history_lastEvaluation: "Última Evaluación",
  history_historyTitle: "Historial de Evaluaciones",
  history_evaluationDate: "Fecha de Evaluación",
  history_viewReportButton: "Ver / Reimprimir Informe",
  history_generatingReport: "Generando Informe...",
  history_noHistory: "No tienes evaluaciones pasadas.",
  history_loading: "Cargando su historial...",
  history_fetchError: "No se pudo cargar su historial de evaluaciones. Por favor, inténtelo de nuevo más tarde.",

  admin_title: "Panel de Administración",
  admin_manageUsers: "Gestionar Usuarios",
  admin_error_load_users: "No se pudo cargar la lista de usuarios. Es posible que no tengas permiso.",
  admin_success_role_update: "Rol de usuario actualizado correctamente.",
  admin_error_role_update: "Ocurrió un error al cambiar el rol.",
  admin_error_self_remove: "No puedes eliminar tu propio estado de administrador.",
  admin_table_header_user: "Usuario",
  admin_table_header_role: "Rol",
  admin_table_header_action: "Acción",
  admin_role_admin: "Admin",
  admin_role_user: "Usuario",
  admin_no_name: "Sin Nombre",
  admin_action_remove: "Quitar Admin",
  admin_action_make: "Hacer Admin",
  
  support_title: "Soporte y Ayuda",
  support_heading: "¿Necesitas Ayuda?",
  support_intro: "Lamentamos que hayas tenido un problema. Nuestro equipo está aquí para ayudarte.",
  support_instruction_email: "Para resolver tu problema lo más rápido posible, por favor envíanos un correo a:",
  support_instruction_include: "Por favor, asegúrate de incluir la siguiente información:",
  support_info_1: "El correo electrónico que usaste para registrarte.",
  support_info_2: "La fecha y hora aproximada de la transacción.",
  support_info_3: "Una breve descripción del problema que experimentaste.",
  support_backToHomeButton: "Volver a la Página Principal",
  
  footer_supportLink: "Soporte",

  report_confidential_title: "Reporte Confidencial de Salud Ocular",
  report_date_generated: "Fecha de Generación",
  report_patient_info: "Información del Paciente",
  report_patient_name: "Nombre",
  report_patient_dob: "Fecha de Nacimiento",
  report_patient_email: "Correo Electrónico",
  report_ai_summary_title: "Resumen Impulsado por IA",
  report_questionnaire_summary: "Resumen del Cuestionario",
  report_image_analysis_details: "Detalles del Análisis de Imagen",
  report_submitted_image: "Imagen Enviada",
  report_no_findings: "El análisis de imagen inicial no detectó signos inmediatos de condiciones mayores basados en la imagen proporcionada.",
  questionnaire_reason: "Motivo de la evaluación",
  questionnaire_lenses: "Usa lentes",
  questionnaire_surgery: "Tuvo cirugía/lesión",
  questionnaire_illnesses: "Enfermedades generales",
  questionnaire_familyHistory: "Historial ocular familiar",
  questionnaire_symptoms: "Síntomas actuales",
  questionnaire_not_answered: "No respondido",
  date_locale: "es-ES",

  language_switcher_en: "EN",
  language_switcher_es: "ES",

  error_generic_api_key_missing: "El servicio de IA no está disponible: Falta la clave de API. Por favor, contacte al soporte.",
  error_generic_api_key_invalid: "El servicio de IA no está disponible: La clave de API configurada no es válida. Por favor, contacte al soporte.",
  error_generic_api_fetch_failed: "Error al obtener consejos debido a un error de API: {errorMessage}",
  error_generic_unexpected_api: "Ocurrió un error inesperado al comunicarse con el servicio de IA. Por favor, inténtelo de nuevo.",
  error_generic_no_tips_received: "No se recibieron consejos de la IA. Por favor, inténtelo de nuevo más tarde.",
  error_analysis_blocked: "El análisis no se pudo completar porque la imagen enviada no era clara o era inapropiada. Por favor, inténtelo de nuevo con una foto clara de solo su ojo.",
};
